import Link from "next/link";
import { and,desc,eq,isNotNull,isNull,sql } from "drizzle-orm";
import { Brand } from "@/components/brand";
import { SeeOperationsControls } from "@/components/see-operations-controls";
import { getDb } from "@/db";
import { missions,missionUpdates,seeReports,scoutProfiles,users,seeOfferEvents } from "@/db/schema";
import { requireAdminUser } from "@/lib/app-user";
import { distanceBetweenZips } from "@/lib/geography";
import { scoutClaimReadinessConditions } from "@/lib/scout-claim-readiness";
import { getStripeLivemode } from "@/lib/stripe";
import { seeDate } from "@/lib/see-opportunities";
import { type SeeSnapshot } from "@/lib/see-it";
import "@/app/see-it.css";
export const metadata={title:"See It Operations | Send a Scout",robots:{index:false,follow:false}};
export const maxDuration=300;
export default async function SeeOperations(){
 await requireAdminUser();const db=getDb();
 const [rows,scouts,offers,notes,metrics]=await Promise.all([
  db.select({mission:missions,report:seeReports}).from(missions).leftJoin(seeReports,and(eq(seeReports.missionId,missions.id),eq(seeReports.revision,missions.seeReportRevision))).where(and(isNotNull(missions.seeTemplateKey),isNull(missions.archivedAt))).orderBy(desc(missions.createdAt)).limit(100),
  db.select({zip:scoutProfiles.homeZip,radius:scoutProfiles.serviceRadiusMiles}).from(scoutProfiles).innerJoin(users,eq(users.id,scoutProfiles.userId)).where(and(...scoutClaimReadinessConditions(getStripeLivemode()),eq(scoutProfiles.canSee,true))),
  db.select().from(seeOfferEvents).orderBy(desc(seeOfferEvents.createdAt)).limit(200),
  db.select({missionId:missionUpdates.missionId,message:missionUpdates.message,createdAt:missionUpdates.createdAt}).from(missionUpdates).where(sql`${missionUpdates.message} LIKE 'Recruiting note:%'`).orderBy(desc(missionUpdates.createdAt)).limit(100),
  db.execute<{completed:number;markets:number;avg_claim_hours:number;avg_contribution:number}>(sql`SELECT count(*) FILTER(WHERE status='completed' AND customer_price_cents>0)::int AS completed,count(DISTINCT lower(city)||','||state) FILTER(WHERE status='completed' AND customer_price_cents>0)::int AS markets,round(avg(extract(epoch from (claimed_at-see_funded_at))/3600)::numeric,1) AS avg_claim_hours,round(avg(customer_price_cents-scout_payout_cents) FILTER(WHERE status='completed')) AS avg_contribution FROM missions WHERE see_template_key IS NOT NULL AND archived_at IS NULL`),
 ]);
 const stats=metrics.rows[0];const money=(cents:number)=>`$${(cents/100).toFixed(2)}`;
 return <main className="see-site"><header className="see-header see-shell"><Brand /><Link href="/control-room">← Control Room</Link></header><section className="see-board see-shell"><span className="see-kicker">SEE IT OPERATIONS</span><h1>Find the Scout.<br />Deliver the picture.</h1><p>{stats?.completed??0} / 100 paid checks completed · {stats?.markets??0} / 25 markets · Average claim: {stats?.avg_claim_hours??"—"} hours · Average price less Scout pay: {stats?.avg_contribution?money(Number(stats.avg_contribution)):"—"} (before processing and operating costs)</p><p>New missions can be funded without local supply. Automatic offers rise at one-third, two-thirds, and five-sixths of the funded window, within the cap. Assignment closes four hours before the completion target. Claimed missions require operational follow-up rather than automatic cancellation.</p>{process.env.SEE_IT_BOOSTS_PAUSED==="true"&&<p className="see-message">All automatic offer increases are paused by configuration.</p>}{!rows.length&&<div className="see-empty">New See It requests will appear here after customers start ordering. Existing missions retain their original workflow.</div>}{rows.map(({mission,report})=>{const contract=mission.seeTemplateSnapshot as SeeSnapshot;const distances=scouts.map(scout=>{const miles=distanceBetweenZips(scout.zip,mission.zip);return miles!==null&&miles<=scout.radius?miles:null;}).filter((v):v is number=>v!==null);const open=mission.status==="open";const overdue=mission.seeDeadlineAt&&mission.seeDeadlineAt<new Date()&&!["completed","cancelled","submitted"].includes(mission.status);
 return <article className="see-form-section" key={mission.id} style={{marginTop:25}}><span className="see-kicker">{open?(distances.some(d=>d<=50)?"FINDING SCOUT":"SUPPLY NEEDED"):overdue?"OVERDUE — FOLLOW UP":mission.status.toUpperCase()}</span><h2 style={{marginTop:12}}>{contract.template.name} · {mission.city}, {mission.state} {mission.zip}</h2><p>Customer {money(mission.customerPriceCents)} · Scout offer {money(mission.scoutPayoutCents)} · Cap {money(mission.seePayoutCapCents??0)}{mission.seeAcceptedPayoutCents!==null?` · Locked at claim ${money(mission.seeAcceptedPayoutCents)}`:""}</p><p>Deadline: {seeDate(mission.seeDeadlineAt,mission.timezone)} · Assignment cutoff: {seeDate(mission.seeAssignmentCutoffAt,mission.timezone)} · {mission.timezone}</p>{open&&<p>Ready Scouts within their own selected travel radius: {distances.filter(d=>d<=10).length} within 10 miles · {distances.filter(d=>d<=25).length} within 25 · {distances.filter(d=>d<=50).length} within 50. Distances use ZIP centers.</p>}{mission.seeExpiredAt&&<p className="see-message">Expired unassigned mission · payment status: {mission.paymentStatus}. {mission.paymentStatus!=="refunded"?"Refund processing must be reconciled until confirmed.":"Refund confirmed."}</p>}{report&&<p><b>Report revision {report.revision}: {report.status}</b>{report.error?` — ${report.error}`:""}{report.reviewNote?` · Review note: ${report.reviewNote}`:""}</p>}<div style={{display:"flex",gap:18,flexWrap:"wrap",fontSize:12,fontWeight:700}}><Link href={`/dashboard/missions/${mission.id}`}>Open private mission →</Link>{open&&<Link href={`/missions/${mission.id}`} target="_blank">Open recruitment page →</Link>}{report?.storagePath&&<Link href={`/api/see-reports/${mission.id}`}>Review PDF →</Link>}</div>{open&&<div className="see-empty" style={{padding:20,marginTop:18}}><b>Recruitment copy</b><p>{money(mission.scoutPayoutCents)} photo mission in {mission.city}, {mission.state} {mission.zip}. {contract.template.minutes} minutes estimated on location. Complete a {contract.template.name.toLowerCase()} by {seeDate(mission.seeDeadlineAt,mission.timezone)} ({mission.timezone}). Review the checklist and required Scout setup: https://www.sendascout.com/missions/{mission.id}</p></div>}<SeeOperationsControls id={mission.id} paused={mission.seeBoostPaused} cap={mission.seePayoutCapCents??0} revision={mission.seeReportRevision} reportStatus={mission.seeReportStatus} open={open}/>{offers.some(event=>event.missionId===mission.id)&&<details className="see-template-tasks"><summary>Offer history</summary>{offers.filter(event=>event.missionId===mission.id).map(event=><p key={event.id}>{seeDate(event.createdAt,mission.timezone)} · {money(event.previousCents)} → {money(event.offeredCents)} · {event.reason}</p>)}</details>}{notes.filter(note=>note.missionId===mission.id).map((note,index)=><p className="see-hint" key={index}>{seeDate(note.createdAt,mission.timezone)} · {note.message}</p>)}</article>;})}</section></main>;
}
