import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdminUser } from "@/lib/app-user";
import { Brand } from "@/components/brand";
import { OutreachForm } from "@/components/outreach-form";
import { cancelOutreachMessage,generateOutreachDraft,queueOutreachMessage,saveOutreachDraft,updateOutreachProspect } from "@/app/actions/outreach";
import { outreachProspectDetail } from "@/lib/outreach-data";
import { segments } from "@/lib/outreach-content";
import styles from "../outreach.module.css";
export const metadata={title:"Prospect | Send a Scout",robots:{index:false,follow:false}};
const when=(value:string|null)=>value?new Date(value).toLocaleString("en-US",{timeZone:"America/New_York"})+" Eastern":"—";
export default async function ProspectPage({params}:{params:Promise<{id:string}>}) {
  await requireAdminUser();const {id}=await params;if(!/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(id))notFound();
  const {prospect:p,messages,bookings}=await outreachProspectDetail(id);if(!p)notFound();
  return <main className="control-page"><header className="control-header"><Brand href="/control-room"/><div><Link href="/control-room/outreach">Outreach CRM</Link><Link href="/control-room">Control Room</Link></div></header><div className={styles.shell}><Link className={styles.back} href="/control-room/outreach">← All prospects</Link>
    <div className={styles.hero}><div><span className={styles.label}>{segments[p.segment]}</span><h1>{p.company}</h1><p>{p.contact_name&&`${p.contact_name} · `}{p.email}{p.location&&` · ${p.location}`}</p><div className={styles.actions}>{p.website&&<a className={styles.link} href={p.website} target="_blank" rel="noreferrer">Business website ↗</a>}{p.source_url&&<a className={styles.link} href={p.source_url} target="_blank" rel="noreferrer">Research source ↗</a>}</div></div><span className={styles.badge}>{p.stage}</span></div>
    {p.suppressed_at&&<p className={styles.notice}>This contact is suppressed from outreach. Imports and stage changes cannot remove that suppression.</p>}
    <div className={styles.grid}><section><div className={styles.card}><div className={styles.formTitle}><h2>Messages</h2><OutreachForm action={generateOutreachDraft} label="Generate tailored draft" disabled={!!p.suppressed_at}><input type="hidden" name="id" value={id}/></OutreachForm></div><p className={styles.muted}>Drafts use your verified opening line and the selected See It service. Review the wording and save edits before approving. Emails include the business address and an unsubscribe link.</p></div>
      {messages.map(m=><article key={m.id} className={styles.card}><div className={styles.formTitle}><h2>{m.followup_of?"Follow-up":"Introduction"}</h2><span className={styles.badge}>{m.status==="accepted"?"Accepted by Google":m.status==="replied"?"Response detected":m.status}</span></div>
        {m.status==="draft"?<><OutreachForm action={saveOutreachDraft} label="Save draft" key={`${m.id}-${m.updated_at}`}><input type="hidden" name="messageId" value={m.id}/><label className={styles.field}>Subject<input name="subject" defaultValue={m.subject} required maxLength={200}/></label><label className={styles.field}>Message<textarea name="body" defaultValue={m.body} required minLength={30} maxLength={10000} rows={13}/></label></OutreachForm><hr className={styles.divider}/><OutreachForm action={queueOutreachMessage} label="Approve saved draft & queue" disabled={!!p.suppressed_at}><input type="hidden" name="messageId" value={m.id}/><label className={styles.check}><input type="checkbox" name="reviewed" value="yes" required/>I have saved and reviewed this draft, confirmed its factual claims, and recorded this recipient’s request or permission below.</label></OutreachForm></>:<><h3>{m.subject}</h3><div className={styles.message}>{m.body}</div></>}
        {m.error&&<p className={styles.notice}>{m.error}</p>}<p className={styles.small}>Created {when(m.created_at)}{m.scheduled_at&&` · Scheduled from ${when(m.scheduled_at)}`}{m.accepted_at&&` · Accepted ${when(m.accepted_at)}`}</p>
        <div className={styles.actions}>{m.google_thread_id&&<a className={styles.link} target="_blank" rel="noreferrer" href={`https://mail.google.com/mail/?authuser=${encodeURIComponent(m.sender_mailbox||"support@sendascout.com")}#all/${encodeURIComponent(m.google_thread_id)}`}>Open conversation in Gmail ↗</a>}
          {m.status==="accepted"&&!m.followup_of&&!messages.some(other=>other.followup_of===m.id)&&<OutreachForm action={generateOutreachDraft} label="Draft one follow-up"><input type="hidden" name="id" value={id}/><input type="hidden" name="parentId" value={m.id}/></OutreachForm>}
          {["draft","queued"].includes(m.status)&&<OutreachForm action={cancelOutreachMessage} label="Cancel message"><input type="hidden" name="messageId" value={m.id}/></OutreachForm>}
        </div></article>)}
      {!messages.length&&<div className={styles.card}><p className={styles.empty}>No messages yet. Generate a draft to start shaping the conversation.</p></div>}
    </section><aside><section className={styles.card}><h2>Research & relationship</h2><OutreachForm action={updateOutreachProspect} label="Save prospect details"><input type="hidden" name="id" value={id}/><label className={styles.field}>Stage<select name="stage" defaultValue={p.stage}>{["new","contacted","replied","interested","customer","closed","unsubscribed"].map(v=><option key={v} value={v}>{v}</option>)}</select></label><label className={styles.field}>Contact permission<select name="permission" defaultValue={p.permission}><option value="research_only">Research only — drafts, no sending</option><option value="requested">Recipient requested information</option><option value="opt_in">Recipient opted in</option></select></label><label className={styles.field}>Request / permission record<textarea name="permissionNote" defaultValue={p.permission_note} rows={3} maxLength={1000} placeholder="When, how, and what they requested or agreed to receive"/></label><label className={styles.field}>Verified opening line<textarea name="researchNote" defaultValue={p.research_note} rows={4} maxLength={1500}/></label><label className={styles.field}>Private notes<textarea name="notes" defaultValue={p.notes} rows={4} maxLength={4000}/></label><label className={styles.field}>Linked customer ID (optional)<input name="linkedCustomerId" defaultValue={p.linked_customer_id||""} placeholder="Account UUID if they use a different email"/></label><p className={styles.small}>Changing prospect details cancels queued messages for review. Existing drafts keep their saved wording.</p></OutreachForm></section>
      <section className={styles.card}><h2>Matched paid missions</h2><p className={styles.muted}>Account matches use this email or the linked customer ID. These can include purchases before outreach; they are not automatically attributed to this campaign.</p>{bookings.length?bookings.map(b=><Link className={styles.row} key={b.id} href={`/dashboard/missions/${b.id}`}><div><strong>{b.title}</strong><small>{when(b.paid_at)} · {b.status}</small><small>Collected after refunds: ${(b.net_cents/100).toFixed(2)} · Allocated Scout pay: ${(b.payout_cents/100).toFixed(2)}</small></div></Link>):<p className={styles.empty}>No matching paid bookings yet.</p>}</section></aside></div>
  </div></main>;
}
