import assert from "node:assert/strict";
import { before,after,test } from "node:test";
import { readMigrationFiles } from "drizzle-orm/migrator";
import { PgDialect } from "drizzle-orm/pg-core";
import { PGlite } from "@electric-sql/pglite";
import { seeBoostSql,seeExpirySql } from "../lib/see-fulfillment-sql.ts";
const db=new PGlite();const dialect=new PgDialect();const customer="10000000-0000-4000-8000-000000000001";const scout="10000000-0000-4000-8000-000000000002";
before(async()=>{for(const migration of readMigrationFiles({migrationsFolder:"./db/migrations"})){for(const statement of migration.sql)await db.exec(statement);}await db.query("INSERT INTO users(id,clerk_user_id,email,role) VALUES($1,'test-customer','customer@example.test','customer'),($2,'test-scout','scout@example.test','scout')",[customer,scout]);});after(()=>db.close());
let counter=1;
async function seed(){const id=`20000000-0000-4000-8000-${String(counter++).padStart(12,"0")}`;await db.query(`INSERT INTO missions(id,customer_id,type,status,payment_status,title,instructions,address_line_1,city,state,zip,customer_price_cents,scout_payout_cents,platform_fee_cents,see_template_key,see_template_snapshot,see_service_level,see_window_hours,see_base_payout_cents,see_payout_cap_cents,see_funded_at,see_deadline_at,see_assignment_cutoff_at) VALUES($1,$2,'see','open','paid','Test check','Complete checklist','Example address','Sample City','NC','28562',3900,2200,1700,'property','{}','standard',72,2200,3400,now()-interval '24 hours',now()+interval '48 hours',now()+interval '44 hours')`,[id,customer]);await db.query(`INSERT INTO payments(mission_id,customer_id,kind,amount_cents,scout_payout_cents,platform_fee_cents,status,livemode,stripe_charge_id,idempotency_key,stripe_transfer_group) VALUES($1,$2,'booking',3900,2200,1700,'paid',false,$3,$4,$4)`,[id,customer,`charge-${id}`,`payment-${id}`]);return id;}
async function run(query:ReturnType<typeof seeBoostSql>){const q=dialect.sqlToQuery(query);return db.query(q.sql,q.params);}
async function state(id:string){return (await db.query<{customer_price_cents:number;scout_payout_cents:number;platform_fee_cents:number;status:string;see_offer_version:number}>("SELECT * FROM missions WHERE id=$1",[id])).rows[0];}
test("all migrations apply and a payout boost atomically updates paid allocation and audit once",async()=>{const id=await seed();const input={id,current:2200,version:0,target:2600,livemode:false};assert.equal((await run(seeBoostSql(input))).rows.length,1);assert.equal((await run(seeBoostSql(input))).rows.length,0);assert.equal((await state(id)).customer_price_cents,3900);assert.equal((await state(id)).scout_payout_cents,2600);const payment=(await db.query<{amount_cents:number;scout_payout_cents:number;platform_fee_cents:number}>("SELECT * FROM payments WHERE mission_id=$1",[id])).rows[0];assert.equal(payment.amount_cents,3900);assert.equal(payment.scout_payout_cents,2600);assert.equal(payment.platform_fee_cents,1300);assert.equal((await db.query("SELECT * FROM see_offer_events WHERE mission_id=$1",[id])).rows.length,1);});
test("caps, paused offers, funding mismatch, refunds, and accepted claims block boosts",async()=>{for(const change of ["see_payout_cap_cents=2400","see_boost_paused=true","status='claimed',scout_id='10000000-0000-4000-8000-000000000002',see_accepted_payout_cents=2200","see_assignment_cutoff_at=now()-interval '1 minute'","see_template_key=NULL","payment_status='pending'"]){const id=await seed();await db.exec(`UPDATE missions SET ${change} WHERE id='${id}'`);assert.equal((await run(seeBoostSql({id,current:2200,version:0,target:2600,livemode:false}))).rows.length,0,change);assert.equal((await state(id)).scout_payout_cents,2200);}const id=await seed();await db.query("UPDATE payments SET scout_payout_cents=2000,platform_fee_cents=1900 WHERE mission_id=$1",[id]);assert.equal((await run(seeBoostSql({id,current:2200,version:0,target:2600,livemode:false}))).rows.length,0);const refundId=await seed();await db.query("INSERT INTO payment_refunds(payment_id,amount_cents,currency,idempotency_key,status) SELECT id,100,'usd','refund-test','pending' FROM payments WHERE mission_id=$1",[refundId]);assert.equal((await run(seeBoostSql({id:refundId,current:2200,version:0,target:2600,livemode:false}))).rows.length,0);});
test("an audit failure rolls back the financial allocation and mission offer",async()=>{const id=await seed();await db.exec("CREATE FUNCTION reject_see_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit unavailable'; END $$; CREATE TRIGGER reject_see_audit BEFORE INSERT ON see_offer_events FOR EACH ROW EXECUTE FUNCTION reject_see_audit();");await assert.rejects(run(seeBoostSql({id,current:2200,version:0,target:2600,livemode:false})),/audit unavailable/);await db.exec("DROP TRIGGER reject_see_audit ON see_offer_events; DROP FUNCTION reject_see_audit();");assert.equal((await state(id)).scout_payout_cents,2200);assert.equal((await db.query<{scout_payout_cents:number}>("SELECT scout_payout_cents FROM payments WHERE mission_id=$1",[id])).rows[0].scout_payout_cents,2200);});
test("expiry closes only an unassigned mission, once, and never cancels a claimed trip",async()=>{const id=await seed();assert.equal((await run(seeExpirySql(id))).rows.length,0);await db.query("UPDATE missions SET see_assignment_cutoff_at=now()-interval '1 minute' WHERE id=$1",[id]);assert.equal((await run(seeExpirySql(id))).rows.length,1);assert.equal((await run(seeExpirySql(id))).rows.length,0);assert.equal((await state(id)).status,"cancelled");const claimed=await seed();await db.query("UPDATE missions SET status='en_route',scout_id=$2,see_accepted_payout_cents=2200,see_assignment_cutoff_at=now()-interval '1 minute' WHERE id=$1",[claimed,scout]);assert.equal((await run(seeExpirySql(claimed))).rows.length,0);assert.equal((await state(claimed)).status,"en_route");});

test("structured submission freezes a single report revision and evidence atomically",async()=>{
 const {seeSubmissionSql}=await import("../lib/see-submission-sql.ts");const id=await seed();await db.query("UPDATE missions SET status='onsite',scout_id=$2,see_accepted_payout_cents=2200 WHERE id=$1",[id,scout]);
 const item=(await db.query<{id:string}>("INSERT INTO mission_checklist_items(mission_id,sequence,prompt,response_type,task_key) VALUES($1,1,'Front exterior','photo','front') RETURNING id",[id])).rows[0];
 const file={path:`mission-results/${id}/front.jpg`,contentType:"image/jpeg",bytes:1234,uploadedAt:new Date().toISOString()};const items=[{id:item.id,prompt:"Front exterior",responseType:"photo",text:"",unavailableReason:"",files:[file]}];
 const snapshot={missionId:id,revision:1,title:"Test",templateName:"Property Check",templateVersion:1,address:"Fictional",timeZone:"America/New_York",submittedAt:new Date().toISOString(),visitAt:null,locationVerified:false,latitude:null,longitude:null,accuracyMeters:null,scoutName:"Scout",scoutId:scout,summary:"Visit documented",requestedFocus:"Exterior",items};
 const query=seeSubmissionSql({id,scoutId:scout,previousRevision:0,now:new Date(),snapshot,items,evidence:[{item_id:item.id,path:file.path,content_type:file.contentType,bytes:file.bytes,kind:"checklist_photo",caption:"Front exterior"}],summary:"Visit documented"});
 assert.equal((await run(query)).rows.length,1);assert.equal((await run(query)).rows.length,0);assert.equal((await state(id)).status,"submitted");
 const reports=await db.query<{revision:number;status:string;snapshot:{items:unknown[]}}>("SELECT * FROM see_reports WHERE mission_id=$1",[id]);assert.equal(reports.rows.length,1);assert.equal(reports.rows[0].revision,1);assert.equal(reports.rows[0].status,"pending");assert.equal(reports.rows[0].snapshot.items.length,1);
 assert.equal((await db.query("SELECT * FROM mission_evidence WHERE mission_id=$1",[id])).rows.length,1);
 // The customer/cron release predicate does not permit confirmation until the report is ready.
 assert.equal((await db.query("UPDATE missions SET status='completed' WHERE id=$1 AND status='submitted' AND see_report_status='ready' AND see_report_released_at IS NOT NULL RETURNING id",[id])).rows.length,0);
});
