import assert from "node:assert/strict";
import test from "node:test";
import { SEE_TEMPLATES, normalizeSeeConfiguration, seeChecklist, seePrice, seeOfferAt, seeResultComplete, safeLocalReturn, seeAlertRadius, type SeeConfiguration } from "../lib/see-it.ts";
import { calculateLegacyMissionAmounts } from "../lib/mission-pricing-core.ts";
const config:SeeConfiguration={templateKey:"property",subject:"Rental exterior",focus:"Yard maintenance",access:"public",accessInstructions:"",visitHours:"Daylight",earliestVisit:"",completeBy:"",serviceLevel:"standard",extraQuestions:[],accessConfirmed:true};
test("new packages include their report without changing historical prices",()=>{assert.deepEqual(seePrice(config),{customer:3900,scout:2200,cap:3400,hours:72});assert.deepEqual(seePrice({...config,templateKey:"vehicle"}),{customer:4900,scout:2800,cap:4400,hours:72});assert.equal(seePrice({...config,serviceLevel:"priority"}).customer,5900);assert.equal(calculateLegacyMissionAmounts("see").customerPriceCents,2900);assert.equal(calculateLegacyMissionAmounts("meet").customerPriceCents,2900);assert.equal(calculateLegacyMissionAmounts("move",0).customerPriceCents,1900);});
test("templates fit their photo allowances, preserve required slots, and add typed questions",()=>{for(const template of SEE_TEMPLATES){assert.equal(new Set(template.tasks.map(t=>t.key)).size,template.tasks.length);assert.ok(template.tasks.filter(t=>t.responseType==="photo").length+(template.key==="vehicle"?3:0)<=template.maxPhotos);assert.ok(template.tasks.filter(t=>t.responseType==="video").length<=template.maxVideos);}const normalized=normalizeSeeConfiguration({...config,extraQuestions:[" Is the sign visible? ",""]});assert.equal(seeChecklist(normalized).at(-1)?.prompt,"Is the sign visible?");assert.equal(seeChecklist(normalized).at(-1)?.responseType,"text");assert.throws(()=>normalizeSeeConfiguration({...config,extraQuestions:Array(6).fill("A question")}));assert.throws(()=>normalizeSeeConfiguration({...config,accessConfirmed:false}));assert.throws(()=>normalizeSeeConfiguration({...config,templateKey:"vehicle"}));});
test("deadline-based offers are monotonic, capped, and stop at the deadline",()=>{const fundedAt=new Date("2026-09-19T00:00:00Z"),deadline=new Date(+fundedAt+72*3600000);const offer=(hours:number,current=2200,cap=3400)=>seeOfferAt({fundedAt,deadline,baseCents:2200,currentCents:current,capCents:cap,now:new Date(+fundedAt+hours*3600000)});assert.equal(offer(23.99),2200);assert.equal(offer(24),2600);assert.equal(offer(48),3000);assert.equal(offer(60),3400);assert.equal(offer(61,2200,2900),2900);assert.equal(offer(25,3000),3000);assert.equal(offer(72,2600),2600);assert.equal(seeAlertRadius(fundedAt,deadline,new Date(+fundedAt+4*3600000)),10);assert.equal(seeAlertRadius(fundedAt,deadline,new Date(+fundedAt+24*3600000)),25);assert.equal(seeAlertRadius(fundedAt,deadline,new Date(+fundedAt+48*3600000)),50);});
test("missing evidence requires an explicit explanation, and return URLs remain local",()=>{assert.equal(seeResultComplete({responseType:"photo",photoCount:0,videoCount:1}),false);assert.equal(seeResultComplete({responseType:"photo",photoCount:0,videoCount:0,unavailableReason:"No"}),false);assert.equal(seeResultComplete({responseType:"photo",photoCount:0,videoCount:0,unavailableReason:"Gate was locked; access unavailable."}),true);assert.equal(safeLocalReturn("//evil.example"),"/dashboard");assert.equal(safeLocalReturn("/\\evil.example"),"/dashboard");assert.equal(safeLocalReturn("/scout?mission=123"),"/scout?mission=123");});
