import Link from "next/link";
import { SeeHeader, SeeFooter } from "@/components/see-site";
import { seeDate, seeOpportunities } from "@/lib/see-opportunities";
export const dynamic = "force-dynamic";
export const metadata = { title: "Photo Missions Near You | Send a Scout", description: "See photo mission payouts, tasks, and deadlines before creating a Scout account.", alternates: { canonical: "/missions" } };
export default async function MissionsPage({ searchParams }: { searchParams: Promise<{ location?: string }> }) {
  const location = ((await searchParams).location ?? "").trim().toLowerCase();
  const all = await seeOpportunities();
  const rows = location ? all.filter(row => `${row.city} ${row.state} ${row.zip}`.toLowerCase().includes(location)) : all;
  return <main className="see-site"><SeeHeader /><section className="see-board see-shell"><span className="see-kicker">REAL WORK. CLEAR EXPECTATIONS.</span><h1>Get paid to be<br />someone’s eyes.</h1><p>Browse funded photo missions before you sign up. See the payout, checklist, and completion target.<br />Complete identity, profile, and payout setup before claiming. A mission remains available to other Scouts until claimed.</p><form className="see-address-form" style={{maxWidth:550}}><label htmlFor="mission-location">Find a city, state, or ZIP</label><div><input id="mission-location" name="location" defaultValue={location} placeholder="City, state abbreviation, or ZIP" /><button className="button">Find missions</button></div></form>{rows.length ? <div className="see-board-grid">{rows.map(row => <article className="see-job" key={row.id}><span className="see-kicker">{row.city}, {row.state} {row.zip}</span><h2>{row.template.name}</h2><div className="see-pay">${(row.payout / 100).toFixed(0)}<small> Scout payout</small></div><p>{row.template.minutes} minutes estimated on location · travel extra<br />Complete by {seeDate(row.deadline,row.timeZone)}<br />{row.timeZone}</p><Link className="button button-small" href={`/missions/${row.id}`}>See the full mission</Link></article>)}</div> : <div className="see-empty"><h2>{location ? "No matching photo missions right now." : "The next mission could be near you."}</h2><p>New See It missions appear here after a customer funds them. You can browse without an account, or set up a Scout profile to receive matching opportunities.</p><Link className="button button-small" href="/scout">Set up your Scout profile</Link>{location && <p><Link className="see-underlink" href="/missions">View all photo missions</Link></p>}</div>}</section><SeeFooter /></main>;
}
