import Link from "next/link";
import { requireAdminUser } from "@/lib/app-user";
import { Brand } from "@/components/brand";
import { OutreachForm } from "@/components/outreach-form";
import { createOutreachProspect,importOutreachProspects,saveOutreachSettings,syncOutreachMailbox,disconnectOutreachMailbox } from "@/app/actions/outreach";
import { outreachProspects,outreachSettings,outreachTotals } from "@/lib/outreach-data";
import { googleOutreachConfigured,GOOGLE_CALLBACK,outreachMailbox } from "@/lib/outreach-google";
import { segments } from "@/lib/outreach-content";
import styles from "./outreach.module.css";
export const metadata={title:"Outreach CRM | Send a Scout",robots:{index:false,follow:false}};
export default async function OutreachPage({searchParams}:{searchParams:Promise<{q?:string;stage?:string;connection?:string}>}) {
  await requireAdminUser();const params=await searchParams;
  const [prospects,settings,stats]=await Promise.all([outreachProspects((params.q||"").slice(0,100),params.stage||""),outreachSettings(),outreachTotals()]);
  const configured=googleOutreachConfigured();
  const connectionMessages:Record<string,string>={connected:"Google Workspace connected. Sending remains paused until you enable it below.",setup:"Google OAuth setup is required before connecting this mailbox.",failed:"The connection did not complete. Try again after checking the Google setup.",permissions:"Grant both sending and read access so replies can stop follow-ups.",mailbox:`Connect the ${outreachMailbox()} Google Workspace account.`};
  return <main className="control-page"><header className="control-header"><Brand href="/control-room"/><div><Link href="/control-room">Control Room</Link><Link href="/control-room/see-it">See It operations</Link><Link href="/control-room/customers">Customers</Link></div></header><div className={styles.shell}>
    <div className={styles.hero}><div><span className={styles.label}>Customer growth</span><h1>Turn a good fit into a first mission.</h1><p>Research businesses, write a useful introduction, and follow the conversation through to a paid check.</p></div><span className={styles.badge}>{settings.paused?"Sending paused":"Sending enabled"} · {settings.daily_limit}/weekday</span></div>
    {params.connection&&connectionMessages[params.connection]&&<p className={styles.notice}>{connectionMessages[params.connection]}</p>}
    {settings.last_error&&<p className={styles.notice}>{settings.last_error}</p>}
    <div className={styles.stats}><Stat label="Prospects" value={stats.prospects}/><Stat label="Drafts / queued" value={`${stats.drafts} / ${stats.queued}`}/><Stat label="Accepted by Google" value={stats.accepted}/><Stat label="Matched paying customers" value={stats.paid_customers}/></div>
    <p className={styles.small}>Matched booking revenue after outreach: ${(stats.net_cents/100).toFixed(2)} after refunds, before Scout pay and other costs. Matched by account email or a linked customer; this is not proof the email caused the purchase. Provider acceptance does not confirm inbox delivery.</p>
    <div className={styles.grid}><div><section className={styles.card}><h2>Your prospects</h2><form className={styles.search}><input name="q" aria-label="Search prospects" placeholder="Search business or email" defaultValue={params.q}/><select name="stage" aria-label="Pipeline stage" defaultValue={params.stage||""}><option value="">Every stage</option>{["new","contacted","replied","interested","customer","closed","unsubscribed"].map(v=><option key={v} value={v}>{v}</option>)}</select><button className="button button-small" type="submit">Search</button></form>
      <div className={styles.list}>{prospects.length?prospects.map(p=><Link className={styles.row} key={p.id} href={`/control-room/outreach/${p.id}`}><div><strong>{p.company}</strong><small>{p.contact_name?p.contact_name+" · ":""}{p.email}</small><small>{segments[p.segment]}{p.location?` · ${p.location}`:""} · {p.message_count} messages</small></div><span>{p.stage}</span></Link>):<div className={styles.empty}>Your next customer starts with a specific reason to reach out.<br/>Add a business and the problem a Scout could help them solve.</div>}</div>{prospects.length===200&&<p className={styles.small}>Showing the 200 most recent matching prospects. Narrow your search to find more.</p>}</section>
      <section className={styles.card}><h2>Add a prospect</h2><p className={styles.muted}>Save researched contacts now. Only recipients with a recorded request or permission can enter automated sending.</p><OutreachForm action={createOutreachProspect} label="Save prospect"><div className={styles.fields}>
        <label>Business name<input name="company" required maxLength={200}/></label><label>Contact name<input name="contactName" maxLength={160}/></label><label>Email<input name="email" type="email" required maxLength={254}/></label><label>Business type<select name="segment">{Object.entries(segments).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>Website<input name="website" type="url" placeholder="https://"/></label><label>Location / markets<input name="location" maxLength={200}/></label><label className={styles.wide}>Opening line based on verified research<textarea name="researchNote" rows={3} maxLength={1500} placeholder="Write an accurate, natural opening line. It will appear in the draft exactly as entered."/></label><label className={styles.wide}>Source URL<input name="sourceUrl" type="url" placeholder="https://the-business-website.com/about"/></label><label className={styles.wide}>Private notes<textarea name="notes" rows={2} maxLength={4000}/></label><input type="hidden" name="permission" value="research_only"/></div></OutreachForm></section>
      <section className={styles.card}><h2>Import a prospect list</h2><p className={styles.muted}>Paste a CSV with up to 100 contacts. Existing email addresses are skipped; imports never overwrite suppression or permission.</p><p className={styles.code}>company,email,contactName,segment,website,location,researchNote,sourceUrl,notes</p><OutreachForm action={importOutreachProspects} label="Import prospects"><label className={styles.field}>CSV contents<textarea name="csv" rows={6} maxLength={200000} required placeholder={'company,email,segment\nExample Company,contact@example.com,property'}/></label></OutreachForm></section>
    </div><aside><section className={styles.card}><h2>Google Workspace</h2><p className={styles.muted}>{settings.connected?`Connected: ${settings.mailbox}`:`Sending mailbox: ${outreachMailbox()}`}</p><p className={styles.muted}>Approved emails send from this mailbox. Replies stay in Gmail; the CRM checks the conversations to stop follow-ups. Existing platform notifications continue through Resend.</p>
      {configured?<a className="button button-small" href="/api/outreach/google/connect">{settings.connected?"Reconnect Google":"Connect Google Workspace"}</a>:<p className={styles.notice}>Google connection setup is needed. Prospect records and drafts are ready to use.</p>}
      <div className={styles.actions}><OutreachForm action={syncOutreachMailbox} label="Check replies & purchases"/>{settings.connected&&<OutreachForm action={disconnectOutreachMailbox} label="Disconnect mailbox"/>}</div>
      <p className={styles.small}>Last mailbox check: {settings.last_sync_at?new Date(settings.last_sync_at).toLocaleString("en-US",{timeZone:"America/New_York"})+" Eastern":"Not connected yet"}</p>
      {!configured&&<details><summary>One-time connection setup</summary><ol className={styles.steps}><li>Use a Google Cloud project owned by your Workspace organization. Enable the Gmail API and configure an Internal OAuth consent screen where available.</li><li>Create a Web application OAuth client with this exact redirect URI:<p className={styles.code}>{GOOGLE_CALLBACK}</p></li><li>Add OUTREACH_GOOGLE_CLIENT_ID, OUTREACH_GOOGLE_CLIENT_SECRET, and a securely generated 64-character hexadecimal OUTREACH_TOKEN_KEY to Production environment settings. Redeploy.</li><li>Return here and authorize {outreachMailbox()}. The app requests send and read access for reply checks; it does not request deletion access.</li></ol><p className={styles.small}>Keep the client secret and encryption key in server environment settings. Do not paste them into prospect notes or chat. A Workspace administrator may need to approve the internal app.</p></details>}
    </section><section className={styles.card}><h2>Campaign controls</h2><OutreachForm action={saveOutreachSettings} label="Save controls"><label className={styles.field}>Daily sending limit<input type="number" name="dailyLimit" min={1} max={40} defaultValue={settings.daily_limit} required/></label><label className={styles.field}>Send a Scout business postal address<textarea name="postalAddress" rows={3} defaultValue={settings.postal_address} maxLength={500} placeholder="Your valid business mailing address"/></label><label className={styles.check}><input type="checkbox" name="enabled" value="yes" defaultChecked={!settings.paused}/>Enable approved sends, Monday–Friday, 9 AM–5 PM Eastern.</label></OutreachForm><p className={styles.small}>A limit controls pacing; it does not authorize unsolicited mass email. Research-only contacts cannot be queued. A response, unsubscribe, or paid booking stops queued introductions and follow-ups. A send already in progress cannot be recalled.</p></section>
    <section className={styles.card}><h2>A useful first conversation</h2><ol className={styles.steps}><li>Record a real reason this business could use a Scout.</li><li>Create and edit the service-specific draft.</li><li>Record their request or permission and review the email.</li><li>Queue the message, then follow replies and paid missions.</li></ol><p className={styles.muted}>One optional follow-up can be drafted and approved for each initial email. It waits at least three days and requires a fresh reply check before sending.</p></section></aside></div>
  </div></main>;
}
function Stat({label,value}:{label:string;value:string|number}){return <div className={styles.stat}><small>{label}</small><strong>{value}</strong></div>;}
