import Link from "next/link";
import { IconArrowLeft, IconAlertTriangle, IconArchive, IconDatabase, IconReceiptRefund, IconScale } from "@tabler/icons-react";
import { Brand } from "@/components/brand";
import { requireAdminUser } from "@/lib/app-user";

export const metadata = { title: "Operations Playbook | Send a Scout", robots: { index: false, follow: false } };

export default async function OperationsProceduresPage() {
  await requireAdminUser();
  return <main className="procedures-page"><header><Brand href="/control-room" /><Link href="/control-room"><IconArrowLeft size={17} /> Control Room</Link></header><div className="procedures-shell">
    <div className="procedures-title"><span className="kicker">Internal · administrator access only</span><h1>Operations playbook</h1><p>Required response, retention, recovery, refund and dispute procedures for Send a Scout. Record material decisions in the mission case and never place card numbers or ID images in notes, email or chat.</p></div>
    <Procedure icon={<IconAlertTriangle size={23} />} title="Incident response" badge="Owner: on-duty administrator"><ol><li><strong>Identify and classify.</strong> Critical: immediate safety threat, account takeover, exposed credentials or widespread outage. High: payment error, private evidence exposure or multiple users blocked. Standard: isolated functional failure without safety or data risk.</li><li><strong>Contain.</strong> Pause affected missions or Scouts, disable compromised credentials, stop the failing workflow, and preserve relevant records. For immediate danger, direct users to 911 before platform support.</li><li><strong>Communicate.</strong> Acknowledge critical incidents within 15 minutes, high incidents within one hour and standard incidents within one business day. Give affected users facts, protective actions and the next update time—never speculate.</li><li><strong>Investigate.</strong> Use the operational alert, Vercel logs, mission timeline, messages, location verification, evidence and provider records. Record timestamps, actions, owners and decisions in an internal case note.</li><li><strong>Recover and review.</strong> Validate the repaired workflow, monitor for recurrence, resolve the Control Room alert, and complete a written review within two business days for critical or high incidents.</li></ol><p className="procedure-callout"><strong>Escalation:</strong> notify ownership immediately for safety, legal demand, suspected breach, chargeback cluster, material outage or possible media inquiry. Contact legal counsel and the insurer when facts may trigger reporting or coverage obligations.</p></Procedure>
    <Procedure icon={<IconArchive size={23} />} title="Evidence retention" badge="Quarterly review"><div className="procedure-table"><div><strong>Mission status, route, timestamps, messages and acceptance</strong><span>Retain 7 years after mission completion or case closure for transaction, tax and dispute support.</span></div><div><strong>Photos and video evidence</strong><span>Retain 180 days after completion; extend while a case, chargeback, legal hold or safety investigation remains open.</span></div><div><strong>Precise check-in/out coordinates</strong><span>Retain 2 years after completion; approximate active location is cleared when sharing stops or the mission ends.</span></div><div><strong>Identity verification result</strong><span>Retain provider reference, result, reviewer and date for 7 years after account closure. Do not store raw ID images in Send a Scout.</span></div><div><strong>Application and exception logs</strong><span>Retain 90 days unless attached to an incident, then retain with the incident record.</span></div><div><strong>Deletion request</strong><span>Verify the requester, delete non-required profile data, and document any legal, tax, fraud, safety or dispute hold.</span></div></div><p className="procedure-callout">Access mission evidence only for mission delivery, support, safety, fraud, legal or dispute work. Administrative access must be necessary, minimal and documented.</p></Procedure>
    <Procedure icon={<IconDatabase size={23} />} title="Backup and recovery" badge="Monthly restore test"><ol><li>Confirm Neon point-in-time restore or scheduled backups are active for the production database and record the available recovery window.</li><li>Confirm Vercel Blob objects are private and inventory evidence objects against database references weekly. Blob evidence requires a separate retention/export plan; database backup alone is not enough.</li><li>Before a schema migration, take or confirm a recoverable database checkpoint and preserve the prior production deployment for rollback.</li><li>Test restoration into an isolated non-production database monthly. Verify users, missions, legal acceptances, cases, notifications and payment ledgers without emailing real users.</li><li>Target recovery objectives: database RPO no more than 24 hours and RTO no more than 4 hours until a stronger provider plan is enabled. Record each test result and remediation.</li></ol><p className="procedure-callout"><strong>Never restore directly over production as the first step.</strong> Restore to an isolated target, verify integrity, then approve a controlled cutover.</p></Procedure>
    <Procedure icon={<IconReceiptRefund size={23} />} title="Refund procedure" badge="Two-person review over $100"><ol><li>Open or locate the mission case and verify the requester, mission, charge, status and stated reason.</li><li>Review instructions, messages, verified status/location events, submitted evidence, customer response and payment-provider record.</li><li>Apply the published policy consistently: unclaimed cancellation is normally full; verified travel or completed work may justify a partial charge; nonperformance, duplicate charge or substantiated material failure may justify a full or partial refund.</li><li>Record the decision, calculation, evidence relied upon and customer/Scout communication in the case. Refunds over $100 or outside policy require a second administrator.</li><li>When Stripe is active, execute the refund against the original charge, save the provider refund ID, adjust or reverse the Scout transfer as permitted, and notify both parties. Until Stripe is active, Control Room amounts are records only and must not be represented as processed.</li><li>Confirm provider success and reconcile the mission, payment ledger and bank settlement. Do not mark a case resolved merely because a refund was requested.</li></ol></Procedure>
    <Procedure icon={<IconScale size={23} />} title="Dispute and chargeback procedure" badge="Preserve evidence immediately"><ol><li>Place the mission and related payout under review. Do not alter or delete messages, evidence, timestamps or status history.</li><li>Separate service complaints, safety reports, payment disputes and unauthorized-charge claims; follow the incident procedure for safety or account compromise.</li><li>Create an evidence packet containing the accepted terms version, mission description, route and timing verification, communications, evidence, completion record, refund history and payment-provider identifiers. Share only what the provider or counsel requires.</li><li>Respond before the provider deadline. Use factual, chronological statements and never mischaracterize test data, location confidence or evidence.</li><li>Record the outcome, fees, refund, Scout payout adjustment and any account action. Repeated fraud, account sharing or falsified progress triggers identity re-verification or suspension.</li><li>For arbitration notices, subpoenas, regulator contact or threatened litigation, preserve the entire record and escalate to counsel before responding beyond acknowledgment.</li></ol></Procedure>
    <section className="procedure-readiness"><h2>Before the first paid mission</h2><label><input type="checkbox" disabled /> Neon backup/PITR and restore window verified</label><label><input type="checkbox" disabled /> Private evidence export/retention process verified</label><label><input type="checkbox" disabled /> Stripe refund, transfer reversal and chargeback webhooks tested</label><label><input type="checkbox" disabled /> Operations alert recipient tested</label><label><input type="checkbox" disabled /> Attorney and insurer reviewed published policies and this procedure</label></section>
    <p className="procedures-note">Operational procedure—not legal advice. Review it with North Carolina counsel, counsel for each applicable service jurisdiction, the payment provider and the company’s insurer before a public paid launch.</p>
  </div></main>;
}

function Procedure({ icon, title, badge, children }: { icon: React.ReactNode; title: string; badge: string; children: React.ReactNode }) {
  return <section className="procedure-card"><div className="procedure-heading"><span>{icon}</span><div><h2>{title}</h2><small>{badge}</small></div></div><div className="procedure-body">{children}</div></section>;
}
