import { PolicyPage } from "@/components/policy-page";

export const metadata = { title: "Privacy Notice | Send a Scout", description: "How Send a Scout uses account, identity, mission, location, communication and payment data." };

export default function PrivacyPage() {
  return <PolicyPage eyebrow="Privacy notice" title="Privacy built around the mission." intro="We collect information needed to verify users, match and document missions, process transactions, protect the marketplace and comply with law." version="2026-08-29-v1">
    <section><h2>Information we collect</h2><p>This may include account contact details, profile and vehicle information, mission addresses and instructions, payment records, private messages, results, ratings, support communications, agreement acceptance records, device and security information, and device-provided location during active work.</p></section>
    <section><h2>Scout identity verification</h2><p>Scout verification may involve a government-issued photo ID, selfie or liveness check, phone verification and verified legal name. We intend to use a specialized identity provider for document collection and verification. Send a Scout’s ordinary database will retain the verification provider, reference, outcome, verified name and date—not a reusable copy of the ID image or full document number. The identity provider processes and retains verification data under its own privacy and security terms.</p></section>
    <section><h2>What customers see</h2><p>After a Scout accepts a mission, the customer may see the Scout’s first name, profile photo, identity-verified indicator, completed-mission count and aggregate rating. Customers do not receive a Scout’s ID document, full legal name, document number, home address, personal phone number or identity-provider record.</p></section>
    <section><h2>Location</h2><p>Scout location sharing is limited to active missions. Customers see an approximate location. We use current location heartbeats for status and verified check-in or route events rather than maintaining a permanent breadcrumb trail, and active location is removed when sharing stops or the mission ends. Certain event timestamps and verification coordinates may remain in the mission record for safety, payment and disputes.</p></section>
    <section><h2>How information is used</h2><p>We use information to authenticate accounts, verify Scouts, match and operate missions, calculate prices and routes, communicate updates, process payments and payouts, prevent fraud, investigate safety or service concerns, comply with legal obligations and improve the marketplace.</p></section>
    <section><h2>Service providers and disclosure</h2><p>Providers may support authentication, identity verification, hosting, databases, private file storage, maps, email, text messaging and payments. We may disclose information when reasonably necessary to operate those services, complete a user-requested transaction, investigate fraud or safety, comply with legal process, protect rights and users, or complete a business reorganization subject to appropriate safeguards. We do not sell government-ID images to customers or Scouts.</p></section>
    <section><h2>Email and text alerts</h2><p>Transactional email updates may be controlled in account settings. Text mission and account alerts require separate affirmative consent and are not a condition of purchasing, requesting or performing a mission. Message frequency varies; carrier message and data rates may apply. You may opt out by replying STOP or through profile settings, and may reply HELP for help. We retain consent and opt-out records needed to honor your choices and comply with messaging rules.</p></section>
    <section><h2>Retention and security</h2><p>We retain transaction, agreement, safety and dispute records only as reasonably needed for the stated purpose, taxes, fraud prevention and legal obligations. Identity documents should remain with the specialized provider and may be redacted or deleted under provider procedures when retention is no longer justified. Administrative access is limited by role and sensitive provider credentials remain server-side. No system can guarantee absolute security.</p></section>
    <section><h2>Your choices</h2><p>You may update profile and notification settings and request access, correction or deletion by contacting support@sendascout.com. We may need to verify the requester and retain certain transaction, agreement, messaging-consent, fraud, safety or legal records. Do not send ID images or payment-card details by ordinary email.</p></section>
    <section><h2>Updates and contact</h2><p>Material changes will be posted and may require renewed acceptance. Privacy questions or requests may be sent to support@sendascout.com.</p></section>
  </PolicyPage>;
}
