"use client";
import { useEffect, useState, useTransition, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { IconArrowRight, IconCheck } from "@tabler/icons-react";
import { createSeeMission, type SeeOrder } from "@/app/actions/see-it";
import { getSeeTemplate, normalizeSeeConfiguration, SEE_TEMPLATES, seePrice, type SeeConfiguration, type SeeTemplateKey } from "@/lib/see-it";
import { defaultMissionTimeZoneForState, US_TIME_ZONE_OPTIONS } from "@/lib/us-time-zones";
import { localDateTimeToUtc } from "@/lib/time";
const DRAFT_KEY = "sendascout-see-order-v1";
export function SeeRequest({ initialCheck, initialAddress = "", signedIn, initialPhone = "", priorityZips = [], initialOrder }: { initialCheck?: string; initialAddress?: string; signedIn: boolean; initialPhone?: string; priorityZips?: string[]; initialOrder?: SeeOrder }) {
  const router = useRouter();
  const [order, setOrder] = useState<SeeOrder>({ address: initialAddress, addressLine2: "", city: "", state: "", zip: "", phone: initialPhone, timeZone: "America/New_York", configuration: { templateKey: getSeeTemplate(initialCheck)?.key ?? "property", subject: "", focus: "", access: "public", accessInstructions: "", visitHours: "", earliestVisit: "", completeBy: "", serviceLevel: "standard", extraQuestions: [], accessConfirmed: false }, ...initialOrder });
  const [restored, setRestored] = useState(false);
  const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  useEffect(() => {
    try { const saved = initialOrder ? null : sessionStorage.getItem(DRAFT_KEY); if (saved) { const draft = JSON.parse(saved) as SeeOrder; if (draft.configuration && getSeeTemplate(draft.configuration.templateKey)) setOrder(current => ({ ...current, ...draft, configuration: { ...current.configuration, ...draft.configuration, ...(initialCheck ? { templateKey: getSeeTemplate(initialCheck)?.key ?? draft.configuration.templateKey } : {}) }, ...(initialAddress ? { address: initialAddress } : {}), phone: draft.phone || initialPhone })); } } catch { /* storage is optional */ }
    setRestored(true);
  }, [initialCheck, initialAddress, initialPhone, initialOrder]);
  useEffect(() => { if (restored) { try { sessionStorage.setItem(DRAFT_KEY, JSON.stringify(order)); } catch { /* keep the active form usable */ } } }, [order, restored]);
  const config = order.configuration; const template = getSeeTemplate(config.templateKey)!; const price = seePrice(config);
  const priorityAvailable = priorityZips.includes(order.zip.trim());
  function field<K extends keyof SeeOrder>(key: K, value: SeeOrder[K]) { setOrder(current => ({ ...current, [key]: value })); }
  function configure<K extends keyof SeeConfiguration>(key: K, value: SeeConfiguration[K]) { setOrder(current => ({ ...current, configuration: { ...current.configuration, [key]: value } })); }
  function choose(key: SeeTemplateKey) { setOrder(current => ({ ...current, configuration: { ...current.configuration, templateKey: key, access: ["vehicle", "purchase"].includes(key) ? "permission" : current.configuration.access } })); }
  let cutoff = "4 hours before the completion target";
  if (config.completeBy) { try { cutoff = new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: order.timeZone }).format(new Date(localDateTimeToUtc(config.completeBy, order.timeZone).getTime() - 4 * 3600000)); } catch { /* invalid date is rejected at submission */ } }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError("");
    try { normalizeSeeConfiguration(config); } catch (e) { setError(e instanceof Error ? e.message : "Check the mission details."); return; }
    if (!signedIn) { router.push(`/sign-in?portal=customer&redirect_url=${encodeURIComponent(`/request?check=${config.templateKey}`)}`); return; }
    startTransition(async () => {
      const result = await createSeeMission(order);
      if (!result.ok) { setError(result.error); return; }
      try { sessionStorage.removeItem(DRAFT_KEY); } catch { /* optional */ }
      window.location.assign(result.checkoutUrl || `/dashboard/missions/${result.id}`);
    });
  }
  return <div className="see-request see-shell"><div className="see-request-intro"><span className="see-kicker">LET’S PUT EYES ON IT</span><h1>What would you like us to check?</h1><p>Choose a starting point. We’ll turn your request into a clear Scout checklist and an organized report.</p></div><form onSubmit={submit} className="see-form-layout"><div className="see-form-fields"><section className="see-form-section"><h2>1. Pick your check</h2><div className="see-options">{SEE_TEMPLATES.map(item => <label className="see-option" key={item.key}><input type="radio" name="template" checked={config.templateKey === item.key} onChange={() => choose(item.key)} /><span><b>{item.name}</b><small>From ${item.priceCents / 100}</small></span></label>)}</div><details className="see-template-tasks"><summary>See the {template.name} checklist</summary><ol>{template.tasks.map(task => <li key={task.key}>{task.prompt}</li>)}</ol></details></section>
      <section className="see-form-section"><h2>2. Where should your Scout go?</h2><label className="see-field">Street address<input required autoComplete="street-address" value={order.address} maxLength={250} onChange={e => field("address",e.target.value)} /></label><label className="see-field">Unit / location detail (optional)<input value={order.addressLine2} maxLength={150} onChange={e => field("addressLine2", e.target.value)} /></label><div className="see-fields-row"><label className="see-field">City<input required value={order.city} maxLength={100} onChange={e => field("city",e.target.value)} /></label><label className="see-field">State<input required value={order.state} minLength={2} maxLength={2} placeholder="NC" autoComplete="address-level1" onChange={e => setOrder(current => ({ ...current, state: e.target.value.toUpperCase(), timeZone: defaultMissionTimeZoneForState(e.target.value) }))} /></label><label className="see-field">ZIP<input required inputMode="numeric" pattern="[0-9]{5}" maxLength={5} value={order.zip} onChange={e => setOrder(current => ({...current, zip: e.target.value, configuration: { ...current.configuration, serviceLevel: "standard" }}))} /></label></div><label className="see-field">Mission time zone<select value={order.timeZone} onChange={e => field("timeZone",e.target.value)}>{US_TIME_ZONE_OPTIONS.map(zone => <option key={zone.value} value={zone.value}>{zone.label}</option>)}</select><small>Confirm this matches the location, especially in states with more than one time zone.</small></label></section>
      <section className="see-form-section"><h2>3. Tell us what matters</h2><label className="see-field">What are we looking at?<input required value={config.subject} maxLength={120} placeholder={config.templateKey === "vehicle" ? "2018 Ford F-150 at the seller’s location" : "Rental house exterior and yard"} onChange={e => configure("subject",e.target.value)} /></label><label className="see-field">Specific areas or details to document<textarea value={config.focus} required={config.templateKey === "custom"} minLength={config.templateKey === "custom" ? 10 : undefined} maxLength={2000} placeholder="What do you want to know? Include the parts or areas that need particular attention." onChange={e => configure("focus",e.target.value)} /></label><label className="see-field">Additional questions (optional)<textarea maxLength={900} value={config.extraQuestions.join("\n")} placeholder="One question per line, up to five." onChange={e => configure("extraQuestions",e.target.value.split("\n"))} /><small>Up to five written questions. Keep the request within one location, {template.minutes} minutes on site, and the included photo/video scope.</small></label></section>
      <section className="see-form-section"><h2>4. Arrange access and timing</h2><label className="see-field">How may your Scout access the location?<select value={config.access} onChange={e => configure("access", e.target.value as "public" | "permission")}><option value="public">Publicly accessible exterior only</option><option value="permission">Owner / seller permission arranged</option></select></label><label className="see-field">Access arrangements and contact details<textarea value={config.accessInstructions} required={config.access === "permission"} minLength={config.access === "permission" ? 10 : undefined} maxLength={1500} placeholder="Who has agreed to meet the Scout? Include their contact details and any location instructions." onChange={e => configure("accessInstructions",e.target.value)} /><small>Exact address, contacts, and private instructions are shared with the assigned Scout.</small></label><label className="see-field">Permitted visit hours (optional)<input value={config.visitHours} maxLength={250} placeholder="For example: daylight hours, Monday–Saturday" onChange={e => configure("visitHours",e.target.value)} /></label><label className="see-field">Service level<select value={config.serviceLevel} onChange={e => configure("serviceLevel",e.target.value as "standard" | "priority")}><option value="standard">Standard — target within 72 hours</option>{priorityAvailable && <option value="priority">Priority — target within 24 hours (+$20)</option>}</select><small>{priorityAvailable ? "Priority is available in this ZIP. Completion is still subject to Scout availability and access." : "Priority is offered only in enabled coverage areas. Standard is available nationwide."}</small></label><label className="see-field">Earliest permitted visit (optional)<input type="datetime-local" value={config.earliestVisit} onChange={e => configure("earliestVisit",e.target.value)} /></label><label className="see-field">Specific completion target (optional)<input type="datetime-local" value={config.completeBy} onChange={e => configure("completeBy",e.target.value)} /><small>Otherwise, the {price.hours}-hour target starts when payment succeeds. Allow 12 hours to 14 days for a specific target.</small></label><label className="see-checkbox"><input type="checkbox" required checked={config.accessConfirmed} onChange={e => configure("accessConfirmed",e.target.checked)} /><span>I have permission for this request and will arrange any required access. My Scout must stay in safe, permitted areas.</span></label></section>
      <section className="see-form-section"><h2>5. Your contact number</h2><p>We’ll use this if we need to clarify your request.</p><label className="see-field">Phone number<input type="tel" required autoComplete="tel" value={order.phone} maxLength={30} onChange={e => field("phone",e.target.value)} /></label></section></div>
      <aside className="see-order-summary"><span className="see-kicker">YOUR CHECK</span><h2>{template.name}</h2><div className="see-price">${price.customer / 100}<small>one location</small></div><ul>{[`Up to ${template.maxPhotos} labeled photos`,`${template.maxVideos} short video${template.maxVideos > 1 ? "s" : ""}`,"Written observations and your questions","Professional PDF report included","Visit details and access limitations"].map(line => <li key={line}><IconCheck size={16} />{line}</li>)}</ul><p><b>{config.serviceLevel === "priority" ? "Priority" : "Standard"} target:</b> {config.completeBy ? `${config.completeBy.replace("T", " at ")} (${order.timeZone})` : `within ${price.hours} hours of payment`}.</p><p><b>Assignment cutoff:</b> {cutoff}{config.completeBy ? ` (${order.timeZone})` : ""}. If still unassigned then, we cancel and initiate a full refund. Refund posting time depends on your bank.</p><p>Completion targets depend on Scout availability and access. If a Scout is already assigned, support will help resolve delays.</p><label className="see-checkbox"><input type="checkbox" required /><span>I understand these fulfillment terms and that this is visual documentation, not a professional inspection or a guarantee of an item or seller.</span></label>{error && <div className="see-message" role="alert">{error}</div>}<button type="submit" className="button" disabled={pending || !restored}>{pending ? "Preparing secure checkout…" : signedIn ? `Continue to payment · $${price.customer / 100}` : "Create account / sign in to continue"}<IconArrowRight size={16} /></button><p className="see-hint">{signedIn ? "Review and pay securely with Stripe. The mission is published only after payment succeeds." : "Your request stays saved in this browser while you sign in."}</p><Link className="see-underlink" href="/sample-report" target="_blank">See the sample report</Link></aside></form></div>;
}
