import Link from "next/link";
import { IconArrowRight, IconCamera, IconCar, IconCheck, IconFileDescription, IconHome, IconMapPin, IconPackage, IconTool, IconEye } from "@tabler/icons-react";
import { Brand } from "@/components/brand";
import { SEE_TEMPLATES, type SeeTemplate } from "@/lib/see-it";
import "@/app/see-it.css";

export const seeIcons = { property: IconHome, vehicle: IconCar, purchase: IconPackage, project: IconTool, custom: IconEye };
export function SeeHeader() {
  return <header className="see-header see-shell"><Brand /><nav aria-label="Main navigation"><Link href="/#checks">What we check</Link><Link href="/#how">How it works</Link><Link href="/missions">Earn as a Scout</Link></nav><div><Link className="see-login" href="/sign-in?redirect_url=/dashboard">Sign in</Link><Link className="button button-small" href="/request">Send a Scout <IconArrowRight size={16} /></Link></div></header>;
}
export function SeeFooter() {
  return <footer className="see-footer see-shell"><div><Brand /><p>Real people. A clearer picture.</p></div><nav aria-label="Footer"><Link href="/missions">Find Scout missions</Link><Link href="/scout">Scout account</Link><Link href="/request?type=move-it">Move It</Link><Link href="/request?type=meet-it">Meet It</Link><Link href="mailto:support@sendascout.com">Support</Link><Link href="/policies">Policies</Link><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link></nav><small>© {new Date().getFullYear()} Send a Scout LLC.</small></footer>;
}
function ReportPreview() {
  return <div className="see-report-scene" aria-label="Illustrative example of a Property Check report">
    <span className="see-scene-label"><span /> YOUR EYES ON LOCATION</span>
    <div className="see-paper"><div className="see-paper-brand"><IconEye size={22} /><b>Send a Scout</b><span>EXAMPLE REPORT</span></div><div className="see-paper-title"><small>SEE IT / PROPERTY</small><h3>A clearer picture.<br />Without the trip.</h3></div>
      <div className="see-house" aria-hidden="true"><svg viewBox="0 0 480 235" fill="none"><rect width="480" height="235" fill="#dcece7"/><circle cx="387" cy="43" r="24" fill="#faf2dc"/><path d="M0 195Q90 166 170 184T480 178V235H0Z" fill="#7fb09c"/><path d="M84 198V116L236 35L390 116V198Z" fill="#f6f3e8"/><path d="M61 121L237 24L415 121" stroke="#244b53" strokeWidth="17" strokeLinejoin="round"/><path d="M263 198V128H324V198" fill="#b78569"/><rect x="119" y="123" width="82" height="48" fill="#7fa3aa"/><path d="M160 123V172M119 147H201" stroke="#fffdf8" strokeWidth="5"/><path d="M270 202L250 235H364L317 202" fill="#ddd7c9"/><circle cx="95" cy="193" r="24" fill="#487a61"/><circle cx="367" cy="193" r="23" fill="#487a61"/></svg><span>Illustrative property • sample data</span></div>
      <div className="see-paper-observation"><span><IconCheck size={16} /> Front exterior documented</span><span><IconCheck size={16} /> Yard condition photographed</span><span><IconCheck size={16} /> Access limitations noted</span></div><div className="see-paper-bottom"><IconFileDescription size={19} /><b>Photos + video + written observations</b></div></div>
    <div className="see-report-tag"><IconFileDescription size={24} /><div><b>One organized PDF.</b><span>Ready to download and share.</span></div></div>
  </div>;
}
export function SeeLanding({ template }: { template?: SeeTemplate }) {
  const href = template ? `/request?check=${template.key}` : "/request";
  return <main className="see-site"><SeeHeader /><section className="see-hero see-shell"><div className="see-hero-copy"><span className="see-kicker"><IconMapPin size={16} /> {template ? template.name.toUpperCase() : "A REAL PERSON. RIGHT THERE."}</span><h1>{template ? <>{template.key === "vehicle" ? "See the vehicle." : template.key === "property" ? "See the property." : template.key === "purchase" ? "See it before\nyou buy it." : template.key === "project" ? "See the progress." : "Need eyes\nsomewhere?"}<em>Skip the trip.</em></> : <>Need eyes<br />somewhere?<em>Send a Scout.</em></>}</h1><p className="see-lede">{template ? template.description : "Get current photos, video, and answers from a real person on location—without making the trip yourself."}</p><form action="/request" className="see-address-form">{template && <input type="hidden" name="check" value={template.key} />}<label htmlFor="hero-address">Where do you need eyes?</label><div><IconMapPin size={21} /><input id="hero-address" name="address" placeholder="Enter the location or street address" autoComplete="street-address" /><button className="button" type="submit">Send a Scout <IconArrowRight size={18} /></button></div></form><p className="see-hero-note">From ${template ? template.priceCents / 100 : 39} · No contract · PDF report included</p><Link className="see-underlink" href="/sample-report">See an example report <IconArrowRight size={16} /></Link></div><ReportPreview /></section>
    <div className="see-benefit-bar"><div className="see-shell"><span><IconCamera size={21} /> Current photos & video</span><span><IconCheck size={21} /> Your questions, answered</span><span><IconFileDescription size={21} /> An organized PDF report</span></div></div>
    {template ? <section className="see-section see-shell see-included"><div><span className="see-kicker">YOUR {template.name.toUpperCase()}</span><h2>Clear instructions.<br />Useful evidence.</h2><p>One location. Up to {template.maxPhotos} photos and {template.maxVideos === 1 ? "a short video" : `${template.maxVideos} short videos`}, plus written observations and up to five additional questions.</p><p>Standard targets completion within 72 hours of funding. You can specify an earlier or later completion target when requesting your check. We’ll show the assignment cutoff before payment.</p><Link className="button" href={href}>Start a {template.name} <IconArrowRight size={18} /></Link></div><ul>{template.tasks.map(task => <li key={task.key}><IconCheck size={18} /><span>{task.prompt}<small>{task.responseType === "text" ? "Written observation" : task.responseType === "video" ? "Video" : "Photo"}</small></span></li>)}</ul></section> : <section id="checks" className="see-section see-shell"><div className="see-section-heading"><div><span className="see-kicker">WHAT CAN A SCOUT CHECK?</span><h2>If you need to see it,<br />start here.</h2></div><p>A property across the state. A vehicle across the country. A project you can’t get to. Tell us where to look.</p></div><div className="see-products">{SEE_TEMPLATES.map((item,index) => { const Icon = seeIcons[item.key];return <Link className={`see-product see-product-${item.key}`} href={`/${item.slug}`} key={item.key}><span className="see-product-index">0{index + 1}</span><Icon size={33} stroke={1.5} /><h3>{item.name}</h3><p>{item.description}</p><div><b>From ${item.priceCents / 100}</b><IconArrowRight size={20} /></div></Link>;})}</div></section>}
    <section id="how" className="see-how"><div className="see-shell"><span className="see-kicker">A SHORTER WAY TO KNOW</span><h2>You pick the place.<br />We find your eyes.</h2><div className="see-steps"><article><span>01</span><h3>Tell us what to check.</h3><p>Choose a check, enter the location, and add the details that matter to you.</p></article><article><span>02</span><h3>A local Scout takes a look.</h3><p>We find a Scout to follow your checklist and capture photos, video, and observations.</p></article><article><span>03</span><h3>Get the whole picture.</h3><p>Review an organized report in your account. Download a clean PDF to share with anyone who needs it.</p></article></div><p className="see-coverage-note">Request a check across the U.S. Availability varies by location. Standard targets 72 hours. If your mission is still unassigned at its stated cutoff, we cancel it and initiate a full refund.</p></div></section>
    <section className="see-section see-shell see-report-pitch"><div><span className="see-kicker">SOMETHING YOU CAN ACTUALLY USE</span><h2>More than a<br />camera roll.</h2><p>Labeled photos. Answers to your questions. A record of the visit and anything the Scout couldn’t check. All brought together in a professional report.</p><Link className="button button-dark" href="/sample-report">View the sample report <IconArrowRight size={18} /></Link></div><div className="see-report-features"><div><b>For you.</b><p>See what was there, when the Scout visited.</p></div><div><b>For your next conversation.</b><p>Share the PDF with a partner, seller, contractor, or property manager.</p></div><div><b>With the limits made clear.</b><p>Scouts document observations. Checks are not mechanical inspections, appraisals, or professional assessments.</p></div></div></section>
    <section className="see-scout-band see-shell"><div><span className="see-kicker">YOUR NEIGHBORHOOD. SOMEONE ELSE’S EYES.</span><h2>Get paid to go look.</h2><p>See the work, payout, and deadline before you create a Scout account. Secure weekly payouts through Stripe.</p></div><Link className="button button-light" href="/missions">Browse photo missions <IconArrowRight size={18} /></Link></section>
    <section className="see-section see-shell see-faq"><div><span className="see-kicker">GOOD QUESTIONS</span><h2>Know what to expect.</h2></div><div>{[
      ["Can I request a check where there aren’t any Scouts yet?", "Yes. We accept See It requests across the U.S. and look for a Scout around each funded mission. Coverage is still growing, so a completion target is not a guarantee. Your checkout states the assignment cutoff and full-refund policy."],
      ["What if the Scout can’t access something?", "Arrange any required access before ordering. Scouts only enter permitted, safe areas. They record access limitations or unavailable evidence for review, and your report makes those limits clear."],
      ["What exactly will I receive?", "The photos and videos specified in your check, written answers, and a downloadable PDF with labeled photos, observations, visit details, and links to video in your account. Any missing evidence is identified."],
      ["Can a Scout tell me whether a car or property is a good purchase?", "Scouts capture what they can observe. They do not diagnose mechanical problems, evaluate structural safety, determine value, or guarantee a seller or item. Use the evidence alongside any professional advice you need."],
    ].map(([q,a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
    <section className="see-other see-shell"><span>More ways to use a Scout</span><Link href="/request?type=move-it">Move It · local pickup & delivery <IconArrowRight size={17} /></Link><Link href="/request?type=meet-it">Meet It · be there for an appointment <IconArrowRight size={17} /></Link><small>Available where Scout coverage permits.</small></section><SeeFooter /></main>;
}
