"use client";
import Link from "next/link";
import Image from "next/image";
import type { SeeReportSnapshot } from "@/lib/see-report-types";
import type { SeeTask } from "@/lib/see-it";
import "@/app/see-it.css";
export type SeeMissionInfo={templateName:string;templateKey:string;maxPhotos:number;maxVideos:number;deadline:string|null;cutoff:string|null;earliest:string|null;reportStatus:string|null;revision:number;releasedAt:string|null;reviewNote:string|null;tasks:SeeTask[];report:SeeReportSnapshot|null};
export function SeeMissionPanel({info,missionId,status,timeZone,role}:{info:SeeMissionInfo;missionId:string;status:string;timeZone:string;role:string}){
 const when=(value:string|null)=>value?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short",timeZone}).format(new Date(value)):"Set after payment";
 return <article className="mission-panel"><span className="see-kicker">{info.templateName}</span><h2>{status==="open"&&role==="customer"?"Finding your Scout":info.reportStatus==="ready"?"Your report is ready":info.reportStatus==="review"?"Evidence is being reviewed":info.reportStatus==="correction"?"A correction has been requested":info.reportStatus?"Preparing your report":"Your structured check"}</h2><p className="see-hint">Completion target: <b>{when(info.deadline)}</b> · {timeZone}{info.earliest&&<> · Earliest visit: {when(info.earliest)}</>}</p>{status==="open"&&<p className="see-hint">We’re looking for a Scout to complete this check. If it remains unassigned at {when(info.cutoff)}, it will be cancelled and a full refund initiated. Completion targets depend on availability and access.</p>}{status==="cancelled"&&<p className="see-hint">This mission is closed. Refund status is available in your payment history.</p>}{info.reportStatus&&info.reportStatus!=="ready"&&<p className="see-hint">Customer approval and automatic payout release wait until the report is ready. {info.reportStatus==="review"?"A missing or unavailable checklist item needs review.":info.reportStatus==="failed"?"We’re resolving a report preparation issue.":""}</p>}{info.reviewNote&&<div className="see-message"><b>Review note:</b> {info.reviewNote}</div>}{info.reportStatus==="ready"&&<><Link className="button" href={`/api/see-reports/${missionId}`}>Download PDF report</Link>{info.releasedAt&&<p className="see-hint">Released {when(info.releasedAt)}. The customer has 24 hours to review and report an issue before automatic completion.</p>}</>}{!info.report&&<details className="see-template-tasks"><summary>What your Scout documents</summary><ol>{info.tasks.map(task=><li key={task.key}>{task.prompt}</li>)}</ol><p className="see-hint">Up to {info.maxPhotos} photos and {info.maxVideos} short video{info.maxVideos>1?"s":""}. Private customer questions and instructions are shared with the assigned Scout.</p></details>}{info.report&&<div className="see-report-checklist"><p>{info.report.summary}</p>{info.report.items.map(item=><details key={item.id}><summary>{item.prompt}{item.unavailableReason?" · limitation recorded":""}</summary>{item.text&&<p>{item.text}</p>}{item.unavailableReason&&<p className="see-message">Not fully checked: {item.unavailableReason}</p>}<div className="result-gallery">{item.files.map(file=>{const url=`/api/mission-results/media?missionId=${missionId}&pathname=${encodeURIComponent(file.path)}`;return file.contentType.startsWith("video/")?<video key={file.path} controls preload="metadata" src={url} />:<a key={file.path} href={url} target="_blank" rel="noreferrer"><Image src={url} alt={item.prompt} width={720} height={540} unoptimized /></a>;})}</div></details>)}</div>}</article>;
}
