"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { upload } from "@vercel/blob/client";
import { loadSeeDraft, saveSeeDraft, submitSeeResults } from "@/app/actions/see-evidence";
import { seeResultComplete } from "@/lib/see-it";
import type { SeeAnswer, SeeDraft } from "@/lib/see-report-types";
import "@/app/see-it.css";
export type SeeFieldTask={id:string;prompt:string;responseType:string;guidance?:string|null};
export function SeeEvidenceForm({missionId,tasks,maxPhotos,maxVideos}:{missionId:string;tasks:SeeFieldTask[];maxPhotos:number;maxVideos:number}) {
  const router=useRouter();const [draft,setDraft]=useState<SeeDraft>({summary:"",answers:tasks.map(task=>({itemId:task.id,text:"",unavailableReason:"",files:[]}))});
  const [ready,setReady]=useState(false);const [busy,setBusy]=useState("");const [error,setError]=useState("");const [saved,setSaved]=useState("");const serial=useRef(Promise.resolve());const active=useRef(true);
  useEffect(()=>{active.current=true;loadSeeDraft(missionId).then(result=>{if(!active.current)return;if(result.ok){if(result.draft)setDraft(result.draft);setReady(true);}else setError(result.error);});return()=>{active.current=false;};},[missionId]);
  const persist = useCallback((value:SeeDraft) => {setSaved("Saving draft…");serial.current=serial.current.then(async()=>{const result=await saveSeeDraft(missionId,value);if(!active.current)return;if(result.ok)setSaved("Draft saved");else{setSaved("Draft not saved");setError(result.error);}}).catch(()=>{setSaved("Draft not saved");setError("Could not save your draft. Check your connection and try again.");});return serial.current;},[missionId]);
  useEffect(()=>{if(!ready)return;const timer=setTimeout(()=>{void persist(draft);},1200);return()=>clearTimeout(timer);},[draft,ready,persist]); // Each save is serialized so an older request cannot overwrite a newer draft.
  function answer(id:string,patch:Partial<SeeAnswer>){setDraft(current=>({...current,answers:current.answers.map(item=>item.itemId===id?{...item,...patch}:item)}));}
  const files=draft.answers.flatMap(item=>item.files);const photos=files.filter(file=>file.contentType.startsWith("image/")).length;const videos=files.filter(file=>file.contentType.startsWith("video/")).length;
  async function addFiles(task:SeeFieldTask,chosen:File[]) {
    if(!chosen.length)return;setBusy(`Uploading ${task.prompt}…`);setError("");let next=draft;
    try {
      const allowed=task.responseType==="photo"?["image/jpeg","image/png","image/webp"]:["video/mp4","video/quicktime","video/webm"];
      if((task.responseType==="photo"?photos:videos)+chosen.length>(task.responseType==="photo"?maxPhotos:maxVideos))throw new Error(`This check includes up to ${maxPhotos} photos and ${maxVideos} videos.`);
      for(const file of chosen){if(!allowed.includes(file.type)||file.size<=0||file.size>(task.responseType==="photo"?10:50)*1024*1024)throw new Error("Use JPG, PNG, or WEBP photos up to 10 MB, or MP4, MOV, or WEBM videos up to 50 MB. Convert HEIC photos before uploading.");
        const ext=file.type==="image/jpeg"?"jpg":file.type==="image/png"?"png":file.type==="image/webp"?"webp":file.type==="video/quicktime"?"mov":file.type==="video/webm"?"webm":"mp4";
        const blob=await upload(`mission-results/${missionId}/${crypto.randomUUID()}.${ext}`,file,{access:"private",handleUploadUrl:"/api/mission-results/upload",clientPayload:JSON.stringify({missionId}),multipart:file.size>5*1024*1024});
        next={...next,answers:next.answers.map(item=>item.itemId===task.id?{...item,files:[...item.files,{path:blob.pathname,contentType:file.type,bytes:file.size,uploadedAt:new Date().toISOString(),deviceTimestamp:new Date(file.lastModified).toISOString()}]}:item)};
        setDraft(next);await persist(next);
      }
    }catch(e){setError(e instanceof Error?e.message:"Upload failed. Completed uploads remain in your draft; retry the remaining files.");}finally{setBusy("");}
  }
  async function submit(){setBusy("Submitting your check…");setError("");try{await serial.current;const result=await submitSeeResults(missionId,draft);if(!result.ok)setError(result.error);else router.refresh();}catch{setError("Could not submit. Your saved draft is still available.");}finally{setBusy("");}}
  const completed=tasks.filter(task=>{const item=draft.answers.find(item=>item.itemId===task.id);return item&&seeResultComplete({responseType:task.responseType,responseText:item.text,photoCount:item.files.filter(f=>f.contentType.startsWith("image/")).length,videoCount:item.files.filter(f=>f.contentType.startsWith("video/")).length,unavailableReason:item.unavailableReason});}).length;
  return <article className="mission-panel"><h2>Your See It checklist</h2><p className="see-hint">{completed} of {tasks.length} items documented · {photos}/{maxPhotos} photos · {videos}/{maxVideos} videos</p><p className="see-hint">Take current, clear evidence at this visit. Files upload when selected and your draft saves as you work. If access is unsafe, restricted, or impossible, explain the limitation. Missing evidence goes to review before customer approval.</p>{!ready&&!error&&<p>Loading your saved draft…</p>}{error&&<p className="see-message" role="alert">{error}</p>}<fieldset disabled={!ready||Boolean(busy)} style={{border:0,padding:0,margin:0,minWidth:0}}>{tasks.map((task,index)=>{const item=draft.answers.find(item=>item.itemId===task.id)??{itemId:task.id,text:"",unavailableReason:"",files:[]};return <section key={task.id} style={{borderTop:"1px solid #dce4dd",paddingBlock:20}}><h3 style={{fontSize:15,margin:"0 0 8px"}}>{index+1}. {task.prompt}</h3><p className="see-hint">{task.guidance}</p>{task.responseType==="text"?<label className="see-field">Your observation<textarea maxLength={3000} rows={3} value={item.text} onChange={e=>answer(task.id,{text:e.target.value})} /></label>:<><label className="see-field">Add {task.responseType==="photo"?"photos":"video"}<input type="file" accept={task.responseType==="photo"?"image/jpeg,image/png,image/webp":"video/mp4,video/quicktime,video/webm"} capture={task.responseType==="photo"?"environment":undefined} multiple onChange={e=>{const chosen=Array.from(e.target.files??[]);e.target.value="";void addFiles(task,chosen);}} /></label><div className="see-draft-media">{item.files.map((file,index)=><div key={file.path}><a href={`/api/mission-results/media?missionId=${missionId}&pathname=${encodeURIComponent(file.path)}`} target="_blank" rel="noreferrer">View {task.responseType} {index+1} · {(file.bytes/1024/1024).toFixed(1)} MB</a><button type="button" className="button button-small button-ghost" onClick={()=>answer(task.id,{files:item.files.filter(f=>f.path!==file.path)})}>Remove</button></div>)}</div></>}
      <label className="see-field">Couldn’t fully check this? Explain why (optional)<textarea maxLength={500} rows={2} placeholder="For example: rear access was locked and the owner could not provide access." value={item.unavailableReason} onChange={e=>answer(task.id,{unavailableReason:e.target.value})} /></label></section>;})}<label className="see-field">Visit summary<textarea maxLength={5000} rows={5} value={draft.summary} onChange={e=>setDraft(current=>({...current,summary:e.target.value}))} placeholder="Summarize what you observed and any important limitations." /></label></fieldset><div className="see-hint" role="status" style={{marginBlock:15}}>{busy||saved}</div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button className="button" disabled={!ready||Boolean(busy)||completed!==tasks.length} onClick={()=>void submit()}>Submit check for report preparation</button><button className="button button-ghost" disabled={!ready||Boolean(busy)} onClick={()=>void persist(draft)}>Save draft</button>{!ready&&error&&<button className="button button-ghost" onClick={()=>window.location.reload()}>Reload saved draft</button>}</div></article>;
}
