"use client";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { addSeeRecruitmentNote,reviewSeeReport,updateSeeOfferSettings } from "@/app/actions/see-operations";
export function SeeOperationsControls({id,paused,cap,revision,reportStatus,open}:{id:string;paused:boolean;cap:number;revision:number;reportStatus:string|null;open:boolean}){
 const router=useRouter();const [pending,start]=useTransition();const [error,setError]=useState("");const [note,setNote]=useState("");const [value,setValue]=useState((cap/100).toFixed(2));const [pause,setPause]=useState(paused);
 function run(action:()=>Promise<{ok:true}|{ok:false;error:string}>){setError("");start(async()=>{const result=await action();if(!result.ok)setError(result.error);else{setNote("");router.refresh();}});}
 return <div style={{marginTop:20}}>{open&&<div style={{display:"flex",gap:20,flexWrap:"wrap"}}><label className="see-field">Scout payout cap ($)<input type="number" min="0" step="0.01" value={value} onChange={e=>setValue(e.target.value)} /></label><label className="see-checkbox"><input type="checkbox" checked={pause} onChange={e=>setPause(e.target.checked)} /> Pause automatic increases</label></div>}<label className="see-field">Review / recruiting note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1500} placeholder="Record the review decision, or recruiting channel and outcome. Review notes are visible to mission participants." /></label><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:15}}>{open&&<button className="button button-small" disabled={pending} onClick={()=>run(()=>updateSeeOfferSettings(id,pause,Math.round(Number(value)*100),note))}>Save offer settings</button>}{["review","failed"].includes(reportStatus??"")&&<><button className="button button-small" disabled={pending} onClick={()=>run(()=>reviewSeeReport(id,revision,"release",note))}>Release reviewed report</button><button className="button button-small button-ghost" disabled={pending} onClick={()=>run(()=>reviewSeeReport(id,revision,"correct",note))}>Request Scout correction</button>{reportStatus==="failed"&&<button className="button button-small button-ghost" disabled={pending} onClick={()=>run(()=>reviewSeeReport(id,revision,"retry",note))}>Retry PDF generation</button>}</>}<button className="button button-small button-ghost" disabled={pending} onClick={()=>run(()=>addSeeRecruitmentNote(id,note))}>Save recruiting note</button></div>{error&&<p className="see-message" role="alert">{error}</p>}</div>;
}
