import { PolicyPage } from "@/components/policy-page";

export const metadata = { title: "Terms of Service | Send a Scout", description: "Terms governing customers, independent Scouts and use of the Send a Scout marketplace." };

export default function TermsPage() {
  return <PolicyPage eyebrow="Terms of service" title="Terms for using Send a Scout." intro="These Terms form a binding agreement between you and Send a Scout. They contain important provisions about independent Scouts, risk, liability, refunds and individual arbitration." version="2026-08-29-v1">
    <section><h2>1. Eligibility and agreement</h2><p>You must be at least 18 years old and legally able to enter a contract. By creating or using an account, submitting or accepting a mission, or clicking acceptance, you agree to these Terms, the Marketplace Policies and the Privacy Notice. You consent to transact electronically and to receive agreements and notices electronically. You must provide accurate, current information and protect your sign-in credentials.</p></section>
    <section><h2>2. Send a Scout’s marketplace role</h2><p>Send a Scout provides technology for customers to request local tasks and for independent Scouts to choose missions. Unless expressly stated otherwise, Send a Scout does not perform missions and is not a party to arrangements made outside the platform. We do not guarantee that a mission will be claimed, completed by a particular time or produce a particular result.</p></section>
    <section><h2>3. Scouts are independent providers</h2><p>Scouts are independent providers, not employees, agents, partners or representatives of Send a Scout. Scouts decide whether to accept a mission and are responsible for lawful and safe performance, necessary licenses, permits, insurance, taxes, equipment and vehicle compliance. Nothing in these Terms guarantees missions, earnings or continued platform access.</p></section>
    <section><h2>4. Customer responsibilities</h2><p>Customers must provide complete, accurate instructions; lawful access to each location; truthful descriptions of items, conditions and risks; and any authorization needed for the Scout to act. Customers may not request unlawful, dangerous, deceptive, regulated or prohibited activity, transportation of people, weapons, controlled substances, hazardous materials, cash, or property they do not lawfully control.</p></section>
    <section><h2>5. Scout responsibilities and identity</h2><p>Scouts must use their true legal identity and may be required to complete government-ID, selfie, phone, payment-account or other verification before approval or continued access. A Scout may not let another person use the account or perform an accepted mission. Scouts must follow mission instructions only when lawful and safe, protect customer information, communicate through the platform and promptly report safety issues or material changes.</p></section>
    <section><h2>6. Pricing, payment, payouts and taxes</h2><p>Customers see the mission price before submission and Scouts see the offered payout before claiming. When payments are active, Send a Scout or its payment provider may authorize or collect the customer total, retain the disclosed platform portion and release the Scout payout after completion. Charges, payout holds, reversals, tips, refunds and disputes are governed by the Marketplace Policies and payment-provider rules. Scouts are responsible for their own taxes and tax reporting.</p></section>
    <section><h2>7. Mission records, location and evidence</h2><p>Status events, route calculations, verified check-in data, approximate active location, messages, photos, video, results and payment events form part of the mission record. These records may be used to operate the service, protect users, investigate complaints and resolve disputes. Users may not falsify, manipulate or interfere with these records.</p></section>
    <section><h2>8. Conduct, safety and account action</h2><p>Fraud, threats, harassment, discrimination, impersonation, off-platform payment circumvention, misuse of personal information and interference with the service are prohibited. A user may decline or stop a mission when reasonably concerned about safety or legality. We may investigate, restrict, pause or terminate accounts, cancel missions, withhold payouts where permitted and preserve relevant records to protect users or comply with law.</p></section>
    <section><h2>8A. Optional text messaging</h2><p>If you separately opt in, Send a Scout may send transactional text messages about mission opportunities, acceptance, status, safety, support and account activity to the mobile number you provide. Message frequency varies and carrier message and data rates may apply. Consent is not a condition of purchasing, requesting or performing a mission. Reply STOP to opt out or HELP for help, or change the setting in your profile. Marketing texts, if ever offered, will require any additional consent required by law.</p></section>
    <section><h2>9. Assumption of risk</h2><p>Local errands and in-person tasks involve inherent risks, including travel, property conditions, interactions with third parties, damaged or unavailable items and inaccurate user-provided information. To the fullest extent permitted by law, each user accepts the risks ordinarily associated with the missions they request or perform and remains responsible for their own acts and omissions. Nothing here excludes responsibility that cannot lawfully be excluded.</p></section>
    <section><h2>10. Disclaimers</h2><p>To the fullest extent permitted by law, the platform is provided “as is” and “as available.” Send a Scout disclaims implied warranties of merchantability, fitness for a particular purpose, title and non-infringement. We do not warrant any user’s identity beyond the scope of completed verification, suitability, licensing, insurance, conduct or work quality, and verification is not a guarantee of future behavior.</p></section>
    <section><h2>11. Limitation of liability</h2><p>To the fullest extent permitted by law, Send a Scout and its owners, officers, personnel and service providers will not be liable for indirect, incidental, special, consequential, exemplary or punitive damages, lost profits, lost data, personal disputes between users, or loss arising from a user’s acts or omissions. Our aggregate liability arising from the platform or a mission will not exceed the greater of (a) the platform fees paid to Send a Scout by you during the six months before the event giving rise to the claim or (b) $100. These limitations do not apply to liability that applicable law does not permit us to limit.</p></section>
    <section><h2>12. Indemnification</h2><p>To the extent permitted by law, you agree to defend, indemnify and hold harmless Send a Scout and its owners, officers, personnel and service providers from third-party claims, losses and reasonable costs arising from your missions, acts or omissions, violation of these Terms, violation of law, misuse of another person’s property or information, or infringement of another person’s rights. This provision does not require a consumer to indemnify Send a Scout for Send a Scout’s own unlawful conduct.</p></section>
    <section><h2>13. Informal dispute resolution</h2><p>Before filing arbitration or court proceedings, the claimant must send a written notice to support@sendascout.com describing the dispute, requested relief and account email, then allow 30 days for a good-faith resolution attempt. Either party may seek temporary emergency relief when necessary to prevent immediate harm.</p></section>
    <section><h2>14. Binding individual arbitration; class and jury waivers</h2><p>Except for eligible small-claims matters, requests for public injunctive relief where applicable law requires court review, and claims that cannot lawfully be arbitrated, disputes arising from these Terms, the platform or a mission will be resolved by binding arbitration on an individual basis under the Federal Arbitration Act. Arbitration will be administered by the American Arbitration Association under the rules applicable to the dispute, may occur remotely, and may be entered as a judgment in a court with jurisdiction. The arbitrator may award the same individual remedies a court could award.</p><p><strong>No class proceedings.</strong> To the fullest extent permitted by law, disputes must proceed individually, not as a class, collective, coordinated, consolidated or representative action. Each party waives a jury trial. If this class waiver is found unenforceable for a particular claim, that claim will proceed in court rather than class arbitration.</p><p><strong>Thirty-day opt out.</strong> You may opt out of arbitration by emailing support@sendascout.com within 30 days after first accepting these Terms. Include your full name, account email and a clear statement that you opt out of the arbitration agreement. Opting out does not affect other Terms or platform access.</p></section>
    <section><h2>15. Governing law and venue</h2><p>The Federal Arbitration Act governs the arbitration provisions. Otherwise, North Carolina law governs without regard to conflict-of-law principles. Court proceedings permitted by these Terms must be brought in a state or federal court with jurisdiction in or serving Craven County, North Carolina, unless applicable law requires another venue.</p></section>
    <section><h2>16. Changes, severability and contact</h2><p>We may update these Terms prospectively. Material changes will be posted and, when appropriate, require renewed acceptance. If a provision is unenforceable, it will be narrowed or severed without affecting the remainder, except as stated in the arbitration section. Questions and legal notices may be sent to support@sendascout.com.</p></section>
  </PolicyPage>;
}
