import { PolicyPage } from "@/components/policy-page";

export const metadata = { title: "Marketplace & Refund Policies | Send a Scout", description: "Mission cancellation, completion, refund, tip and dispute policies for Send a Scout." };

export default function PoliciesPage() {
  return <PolicyPage eyebrow="Marketplace & refund policies" title="Clear rules for every mission." intro="These Policies govern cancellations, refunds, completion review, disputes and prohibited missions. They are incorporated into the Terms of Service." version="2026-08-29-v1">
    <section><h2>Before a Scout claims</h2><p>A customer may cancel an unclaimed mission for a full refund of amounts collected for that mission. A temporary card authorization may take the payment provider or issuing bank additional time to disappear.</p></section>
    <section><h2>After a Scout claims</h2><p>If a customer cancels before verified travel or work begins, the customer ordinarily receives a full refund. Once verified travel, waiting or work begins, a reasonable cancellation charge may be deducted to compensate the Scout and cover costs already incurred. Any charge will not exceed the mission total and will be based on the available mission record.</p></section>
    <section><h2>Scout cancellations and no-shows</h2><p>A Scout who cannot perform an accepted mission must cancel promptly. If the Scout cancels, does not appear, materially misrepresents progress or cannot complete the mission, the customer may receive a full or partial refund. Repeated avoidable cancellations, account sharing or false status updates may result in suspension or removal.</p></section>
    <section><h2>Results and 24-hour review</h2><p>After results are submitted, the customer has 24 hours to confirm completion or report a material problem. If no action is taken, the mission may be automatically completed and the Scout payout may be released. Automatic completion does not prevent a prompt, good-faith support request, but delay can limit available remedies after funds are disbursed.</p></section>
    <section><h2>Refund eligibility</h2><p>Full or partial refunds may be appropriate when a mission was not performed, materially departed from the posted instructions, involved substantiated fraud or duplicate billing, or could not be completed for reasons attributable to the Scout or platform. Refunds generally are not available for dissatisfaction unrelated to the instructions, conditions accurately disclosed before acceptance, customer-provided errors, third-party conduct outside the Scout’s control, or a completed service that delivered the requested work.</p></section>
    <section><h2>How disputes are reviewed</h2><p>Send a Scout may consider the mission description, messages, route and timestamp data, verified check-in events, submitted evidence, customer response and payment record. We may request additional information, pause a payout, issue a full or partial refund, deny a refund, provide a credit, or take account action. A marketplace decision does not waive rights that cannot legally be waived.</p></section>
    <section><h2>Tips, chargebacks and processing</h2><p>Tips are optional and intended for the Scout. A tip may be reversed for fraud, duplicate processing, payment failure or a refund required by law. Users should contact support before initiating a chargeback so the mission record can be reviewed. Chargebacks may pause related payouts and account activity while investigated. Bank and payment-provider processing times are outside Send a Scout’s control.</p></section>
    <section><h2>Safety and prohibited missions</h2><p>Scouts may decline or stop unsafe, illegal, regulated, age-restricted or materially misrepresented work. Customers must not request transport of people, weapons, controlled substances, hazardous materials, cash, unlawful surveillance, entry without authorization, or pickup or delivery of property not lawfully purchased or controlled.</p></section>
    <section><h2>Contact</h2><p>Report a cancellation or refund issue promptly through the mission record and at hello@sendascout.com. Include the mission title, account email and a concise description; do not email government-ID images, card numbers or other unnecessary sensitive information.</p></section>
  </PolicyPage>;
}
