import { sql } from "drizzle-orm";
import {
  type AnyPgColumn,
  boolean,
  check,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

export const userRole = pgEnum("user_role", ["customer", "scout", "admin"]);
export const accountStatus = pgEnum("account_status", ["pending", "active", "suspended"]);
export const scoutStatus = pgEnum("scout_status", ["applicant", "review", "approved", "paused", "rejected"]);
export const verificationStatus = pgEnum("verification_status", ["not_started", "pending", "clear", "review", "failed"]);
export const missionType = pgEnum("mission_type", ["see", "move", "meet"]);
export const missionStatus = pgEnum("mission_status", [
  "draft",
  "open",
  "claimed",
  "en_route",
  "onsite",
  "en_route_pickup",
  "at_pickup",
  "en_route_dropoff",
  "at_dropoff",
  "submitted",
  "completed",
  "cancelled",
  "disputed",
]);
export const paymentStatus = pgEnum("payment_status", ["unpaid", "authorized", "paid", "refunded", "failed"]);
export const notificationChannel = pgEnum("notification_channel", ["in_app", "sms", "email"]);
export const notificationStatus = pgEnum("notification_status", ["pending", "sent", "failed"]);

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  clerkUserId: text("clerk_user_id").notNull(),
  role: userRole("role").notNull().default("customer"),
  status: accountStatus("status").notNull().default("active"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  email: text("email").notNull(),
  phone: text("phone"),
  addressLine1: text("address_line_1"),
  addressLine2: text("address_line_2"),
  city: text("city"),
  state: text("state"),
  zip: text("zip"),
  profileCompletedAt: timestamp("profile_completed_at", { withTimezone: true }),
  emailNotificationsEnabled: boolean("email_notifications_enabled").notNull().default(true),
  smsNotificationsEnabled: boolean("sms_notifications_enabled").notNull().default(false),
  smsConsentedAt: timestamp("sms_consented_at", { withTimezone: true }),
  legalVersion: text("legal_version"),
  legalAcceptedAt: timestamp("legal_accepted_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("users_clerk_user_id_idx").on(table.clerkUserId),
  uniqueIndex("users_email_idx").on(table.email),
]);

export const legalAcceptances = pgTable("legal_acceptances", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  role: userRole("role").notNull(),
  legalVersion: text("legal_version").notNull(),
  termsVersion: text("terms_version").notNull(),
  privacyVersion: text("privacy_version").notNull(),
  policiesVersion: text("policies_version").notNull(),
  arbitrationAccepted: boolean("arbitration_accepted").notNull(),
  electronicRecordsAccepted: boolean("electronic_records_accepted").notNull(),
  source: text("source").notNull().default("web"),
  userAgent: text("user_agent"),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("legal_acceptances_user_version_idx").on(table.userId, table.legalVersion),
  index("legal_acceptances_user_idx").on(table.userId),
]);

export const scoutProfiles = pgTable("scout_profiles", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  status: scoutStatus("status").notNull().default("applicant"),
  backgroundCheck: verificationStatus("background_check").notNull().default("not_started"),
  identityCheck: verificationStatus("identity_check").notNull().default("not_started"),
  identityProvider: text("identity_provider"),
  identityVerificationReference: text("identity_verification_reference"),
  identityVerifiedName: text("identity_verified_name"),
  identityVerifiedAt: timestamp("identity_verified_at", { withTimezone: true }),
  identityVerifiedBy: uuid("identity_verified_by").references(() => users.id),
  homeZip: text("home_zip"),
  serviceRadiusMiles: integer("service_radius_miles").notNull().default(25),
  vehicleType: text("vehicle_type"),
  experience: text("experience"),
  canSee: boolean("can_see").notNull().default(true),
  canMove: boolean("can_move").notNull().default(true),
  canMeet: boolean("can_meet").notNull().default(true),
  stripeAccountId: text("stripe_account_id"),
  payoutsEnabled: boolean("payouts_enabled").notNull().default(false),
  verificationConsentedAt: timestamp("verification_consented_at", { withTimezone: true }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  rating: numeric("rating", { precision: 3, scale: 2 }),
  ratingCount: integer("rating_count").notNull().default(0),
  completedMissions: integer("completed_missions").notNull().default(0),
  headshotPath: text("headshot_path"),
  headshotUploadWindowStartedAt: timestamp("headshot_upload_window_started_at", { withTimezone: true }),
  headshotUploadCount: integer("headshot_upload_count").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("scout_profiles_user_id_idx").on(table.userId),
  check("scout_profiles_headshot_upload_count_check", sql`${table.headshotUploadCount} >= 0`),
]);

export const businessAccounts = pgTable("business_accounts", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerUserId: uuid("owner_user_id").notNull().references(() => users.id),
  name: text("name").notNull(),
  status: text("status").notNull().default("active"),
  plan: text("plan").notNull().default("free"),
  billingEmail: text("billing_email"),
  stripeCustomerId: text("stripe_customer_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("business_accounts_owner_idx").on(table.ownerUserId),
  uniqueIndex("business_accounts_stripe_customer_idx").on(table.stripeCustomerId),
  check("business_accounts_status_check", sql`${table.status} IN ('active', 'paused', 'closed')`),
]);

export const businessMembers = pgTable("business_members", {
  id: uuid("id").defaultRandom().primaryKey(),
  businessAccountId: uuid("business_account_id").notNull().references(() => businessAccounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  role: text("role").notNull().default("requester"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("business_members_account_user_idx").on(table.businessAccountId, table.userId),
  index("business_members_user_idx").on(table.userId),
  check("business_members_role_check", sql`${table.role} IN ('owner', 'admin', 'requester', 'viewer')`),
]);

export const customerSavedLocations = pgTable("customer_saved_locations", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  businessAccountId: uuid("business_account_id").references(() => businessAccounts.id, { onDelete: "cascade" }),
  label: text("label").notNull(),
  addressLine1: text("address_line_1").notNull(),
  addressLine2: text("address_line_2"),
  city: text("city").notNull(),
  state: text("state").notNull().default("NC"),
  zip: text("zip").notNull(),
  latitude: numeric("latitude", { precision: 9, scale: 6 }),
  longitude: numeric("longitude", { precision: 9, scale: 6 }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("customer_saved_locations_customer_idx").on(table.customerId),
  index("customer_saved_locations_business_idx").on(table.businessAccountId),
]);

export const missionTemplates = pgTable("mission_templates", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  businessAccountId: uuid("business_account_id").references(() => businessAccounts.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  type: missionType("type").notNull(),
  configurationJson: jsonb("configuration_json").$type<Record<string, unknown>>().notNull(),
  preferredScoutId: uuid("preferred_scout_id").references(() => users.id, { onDelete: "set null" }),
  lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_templates_customer_idx").on(table.customerId),
  index("mission_templates_business_idx").on(table.businessAccountId),
]);

export const missionRecurrences = pgTable("mission_recurrences", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  businessAccountId: uuid("business_account_id").references(() => businessAccounts.id, { onDelete: "cascade" }),
  templateId: uuid("template_id").notNull().references(() => missionTemplates.id, { onDelete: "cascade" }),
  status: text("status").notNull().default("active"),
  recurrenceRule: text("recurrence_rule").notNull(),
  timezone: text("timezone").notNull().default("America/New_York"),
  startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
  endsAt: timestamp("ends_at", { withTimezone: true }),
  nextRunAt: timestamp("next_run_at", { withTimezone: true }),
  lastRunAt: timestamp("last_run_at", { withTimezone: true }),
  preferredScoutId: uuid("preferred_scout_id").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_recurrences_due_idx").on(table.status, table.nextRunAt),
  index("mission_recurrences_customer_idx").on(table.customerId),
  check("mission_recurrences_status_check", sql`${table.status} IN ('active', 'paused', 'ended')`),
]);

export const missionBundles = pgTable("mission_bundles", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id),
  businessAccountId: uuid("business_account_id").references(() => businessAccounts.id, { onDelete: "set null" }),
  title: text("title").notNull(),
  status: text("status").notNull().default("draft"),
  activeSequence: integer("active_sequence").notNull().default(1),
  listCustomerPriceCents: integer("list_customer_price_cents").notNull().default(0),
  bundleDiscountCents: integer("bundle_discount_cents").notNull().default(0),
  customerPriceCents: integer("customer_price_cents").notNull().default(0),
  scoutPayoutCents: integer("scout_payout_cents").notNull().default(0),
  platformFeeCents: integer("platform_fee_cents").notNull().default(0),
  paymentStatus: paymentStatus("payment_status").notNull().default("unpaid"),
  stripePaymentIntentId: text("stripe_payment_intent_id"),
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_bundles_customer_idx").on(table.customerId),
  index("mission_bundles_business_idx").on(table.businessAccountId),
  index("mission_bundles_status_idx").on(table.status),
  uniqueIndex("mission_bundles_payment_intent_idx").on(table.stripePaymentIntentId),
  check("mission_bundles_status_check", sql`${table.status} IN ('draft', 'open', 'claimed', 'in_progress', 'submitted', 'completed', 'cancelled', 'disputed')`),
  check("mission_bundles_active_sequence_check", sql`${table.activeSequence} > 0`),
  check("mission_bundles_amounts_check", sql`${table.listCustomerPriceCents} >= 0 AND ${table.bundleDiscountCents} >= 0 AND ${table.customerPriceCents} >= 0 AND ${table.scoutPayoutCents} >= 0 AND ${table.platformFeeCents} >= 0 AND ${table.bundleDiscountCents} <= ${table.listCustomerPriceCents} AND ${table.customerPriceCents} = ${table.listCustomerPriceCents} - ${table.bundleDiscountCents} AND ${table.platformFeeCents} = ${table.customerPriceCents} - ${table.scoutPayoutCents}`),
]);

export const missions = pgTable("missions", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id),
  scoutId: uuid("scout_id").references(() => users.id),
  bundleId: uuid("bundle_id").references(() => missionBundles.id),
  bundleSequence: integer("bundle_sequence"),
  predecessorMissionId: uuid("predecessor_mission_id").references((): AnyPgColumn => missions.id, { onDelete: "set null" }),
  sourceMissionId: uuid("source_mission_id").references((): AnyPgColumn => missions.id, { onDelete: "set null" }),
  templateId: uuid("template_id").references(() => missionTemplates.id, { onDelete: "set null" }),
  recurrenceId: uuid("recurrence_id").references(() => missionRecurrences.id, { onDelete: "set null" }),
  recurrenceOccurrenceAt: timestamp("recurrence_occurrence_at", { withTimezone: true }),
  preferredScoutId: uuid("preferred_scout_id").references(() => users.id, { onDelete: "set null" }),
  preferredScoutExclusiveUntil: timestamp("preferred_scout_exclusive_until", { withTimezone: true }),
  preferredScoutBroadcastAt: timestamp("preferred_scout_broadcast_at", { withTimezone: true }),
  scoutDisplayNameSnapshot: text("scout_display_name_snapshot"),
  scoutHeadshotPathSnapshot: text("scout_headshot_path_snapshot"),
  scoutIdentityVerifiedAtSnapshot: timestamp("scout_identity_verified_at_snapshot", { withTimezone: true }),
  type: missionType("type").notNull(),
  status: missionStatus("status").notNull().default("draft"),
  title: text("title").notNull(),
  instructions: text("instructions").notNull(),
  addressLine1: text("address_line_1").notNull(),
  addressLine2: text("address_line_2"),
  city: text("city").notNull(),
  state: text("state").notNull().default("NC"),
  zip: text("zip").notNull(),
  pickupName: text("pickup_name"),
  pickupInstructions: text("pickup_instructions"),
  dropoffName: text("dropoff_name"),
  dropoffAddressLine1: text("dropoff_address_line_1"),
  dropoffAddressLine2: text("dropoff_address_line_2"),
  dropoffCity: text("dropoff_city"),
  dropoffState: text("dropoff_state"),
  dropoffZip: text("dropoff_zip"),
  deliveryInstructions: text("delivery_instructions"),
  deliveryPinRequired: boolean("delivery_pin_required").notNull().default(false),
  deliveryPinHash: text("delivery_pin_hash"),
  deliveryPinHint: text("delivery_pin_hint"),
  deliveryPinFailedAttempts: integer("delivery_pin_failed_attempts").notNull().default(0),
  deliveryPinLockedUntil: timestamp("delivery_pin_locked_until", { withTimezone: true }),
  deliveryPinVerifiedAt: timestamp("delivery_pin_verified_at", { withTimezone: true }),
  deliveryPinVerifiedBy: uuid("delivery_pin_verified_by").references(() => users.id, { onDelete: "set null" }),
  proofOfDeliveryRequired: boolean("proof_of_delivery_required").notNull().default(false),
  enhancedReportRequested: boolean("enhanced_report_requested").notNull().default(false),
  resultUploadTokenCount: integer("result_upload_token_count").notNull().default(0),
  largeItem: boolean("large_item").notNull().default(false),
  scheduledFor: timestamp("scheduled_for", { withTimezone: true }),
  pickupLatitude: numeric("pickup_latitude", { precision: 9, scale: 6 }),
  pickupLongitude: numeric("pickup_longitude", { precision: 9, scale: 6 }),
  dropoffLatitude: numeric("dropoff_latitude", { precision: 9, scale: 6 }),
  dropoffLongitude: numeric("dropoff_longitude", { precision: 9, scale: 6 }),
  routeDistanceMeters: integer("route_distance_meters"),
  routeDurationSeconds: integer("route_duration_seconds"),
  routePolyline: text("route_polyline"),
  routeSource: text("route_source").notNull().default("fixed"),
  routeQuotedAt: timestamp("route_quoted_at", { withTimezone: true }),
  meetAuthorizedMinutes: integer("meet_authorized_minutes").notNull().default(60),
  maximumCustomerPriceCents: integer("maximum_customer_price_cents"),
  maximumScoutPayoutCents: integer("maximum_scout_payout_cents"),
  billableStartedAt: timestamp("billable_started_at", { withTimezone: true }),
  billableEndedAt: timestamp("billable_ended_at", { withTimezone: true }),
  billableLastVerifiedAt: timestamp("billable_last_verified_at", { withTimezone: true }),
  billableMinutes: integer("billable_minutes"),
  chargedMinutes: integer("charged_minutes"),
  verifiedCheckInAt: timestamp("verified_check_in_at", { withTimezone: true }),
  verifiedCheckInLatitude: numeric("verified_check_in_latitude", { precision: 9, scale: 6 }),
  verifiedCheckInLongitude: numeric("verified_check_in_longitude", { precision: 9, scale: 6 }),
  verifiedCheckInAccuracyMeters: integer("verified_check_in_accuracy_meters"),
  verifiedCheckOutAt: timestamp("verified_check_out_at", { withTimezone: true }),
  verifiedCheckOutLatitude: numeric("verified_check_out_latitude", { precision: 9, scale: 6 }),
  verifiedCheckOutLongitude: numeric("verified_check_out_longitude", { precision: 9, scale: 6 }),
  verifiedCheckOutAccuracyMeters: integer("verified_check_out_accuracy_meters"),
  customerPriceCents: integer("customer_price_cents").notNull(),
  listCustomerPriceCents: integer("list_customer_price_cents"),
  bundleDiscountCents: integer("bundle_discount_cents").notNull().default(0),
  scoutPayoutCents: integer("scout_payout_cents").notNull(),
  platformFeeCents: integer("platform_fee_cents").notNull(),
  paymentStatus: paymentStatus("payment_status").notNull().default("unpaid"),
  stripePaymentIntentId: text("stripe_payment_intent_id"),
  locationSharingActive: boolean("location_sharing_active").notNull().default(false),
  scoutLatitude: numeric("scout_latitude", { precision: 9, scale: 6 }),
  scoutLongitude: numeric("scout_longitude", { precision: 9, scale: 6 }),
  scoutLocationAccuracyMeters: integer("scout_location_accuracy_meters"),
  scoutLocationUpdatedAt: timestamp("scout_location_updated_at", { withTimezone: true }),
  claimedAt: timestamp("claimed_at", { withTimezone: true }),
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  archivedReason: text("archived_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("missions_status_idx").on(table.status),
  index("missions_customer_idx").on(table.customerId),
  index("missions_scout_idx").on(table.scoutId),
  index("missions_zip_idx").on(table.zip),
  index("missions_archived_idx").on(table.archivedAt),
  index("missions_bundle_idx").on(table.bundleId),
  uniqueIndex("missions_bundle_sequence_idx").on(table.bundleId, table.bundleSequence),
  index("missions_predecessor_idx").on(table.predecessorMissionId),
  index("missions_template_idx").on(table.templateId),
  index("missions_recurrence_idx").on(table.recurrenceId),
  uniqueIndex("missions_recurrence_occurrence_idx").on(table.recurrenceId, table.recurrenceOccurrenceAt),
  index("missions_preferred_scout_idx").on(table.preferredScoutId, table.preferredScoutExclusiveUntil),
  check("missions_bundle_pair_check", sql`(${table.bundleId} IS NULL AND ${table.bundleSequence} IS NULL) OR (${table.bundleId} IS NOT NULL AND ${table.bundleSequence} IS NOT NULL AND ${table.bundleSequence} > 0)`),
  check("missions_delivery_pin_check", sql`NOT ${table.deliveryPinRequired} OR (${table.type} = 'move' AND ${table.deliveryPinHash} IS NOT NULL)`),
  check("missions_delivery_pin_attempts_check", sql`${table.deliveryPinFailedAttempts} >= 0`),
  check("missions_result_upload_token_count_check", sql`${table.resultUploadTokenCount} >= 0 AND ${table.resultUploadTokenCount} <= 30`),
  check("missions_proof_delivery_check", sql`NOT ${table.proofOfDeliveryRequired} OR ${table.type} = 'move'`),
  check("missions_financial_amounts_check", sql`${table.customerPriceCents} >= 0 AND ${table.scoutPayoutCents} >= 0 AND ${table.platformFeeCents} >= 0 AND ${table.customerPriceCents} = ${table.scoutPayoutCents} + ${table.platformFeeCents}`),
  check("missions_feature_pricing_check", sql`${table.bundleDiscountCents} >= 0 AND (${table.listCustomerPriceCents} IS NULL OR (${table.listCustomerPriceCents} >= 0 AND ${table.bundleDiscountCents} <= ${table.listCustomerPriceCents}))`),
]);

export const missionUpdates = pgTable("mission_updates", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  authorId: uuid("author_id").references(() => users.id),
  status: missionStatus("status"),
  message: text("message"),
  mediaUrl: text("media_url"),
  evidenceKind: text("evidence_kind"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [index("mission_updates_mission_idx").on(table.missionId)]);

export const customerPreferredScouts = pgTable("customer_preferred_scouts", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  scoutId: uuid("scout_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  sourceMissionId: uuid("source_mission_id").references(() => missions.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("customer_preferred_scouts_pair_idx").on(table.customerId, table.scoutId),
  index("customer_preferred_scouts_scout_idx").on(table.scoutId),
  check("customer_preferred_scouts_distinct_users_check", sql`${table.customerId} <> ${table.scoutId}`),
]);

export const missionChangeOrders = pgTable("mission_change_orders", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  proposedByUserId: uuid("proposed_by_user_id").notNull().references(() => users.id),
  kind: text("kind").notNull(),
  status: text("status").notNull().default("pending"),
  description: text("description").notNull(),
  customerDeltaCents: integer("customer_delta_cents").notNull().default(0),
  scoutDeltaCents: integer("scout_delta_cents").notNull().default(0),
  platformDeltaCents: integer("platform_delta_cents").notNull().default(0),
  linkedMissionId: uuid("linked_mission_id").references(() => missions.id, { onDelete: "set null" }),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  approvedByUserId: uuid("approved_by_user_id").references(() => users.id, { onDelete: "set null" }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  declinedAt: timestamp("declined_at", { withTimezone: true }),
  fulfilledAt: timestamp("fulfilled_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_change_orders_mission_idx").on(table.missionId),
  index("mission_change_orders_status_idx").on(table.status),
  uniqueIndex("mission_change_orders_one_pending_idx").on(table.missionId).where(sql`${table.status} = 'pending'`),
  check("mission_change_orders_status_check", sql`${table.status} IN ('pending', 'approved', 'declined', 'expired', 'fulfilled', 'cancelled')`),
  check("mission_change_orders_amounts_check", sql`${table.customerDeltaCents} >= 0 AND ${table.scoutDeltaCents} >= 0 AND ${table.platformDeltaCents} >= 0 AND ${table.customerDeltaCents} = ${table.scoutDeltaCents} + ${table.platformDeltaCents}`),
]);

export const missionPartResults = pgTable("mission_part_results", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  status: text("status").notNull().default("draft"),
  summary: text("summary"),
  submittedByUserId: uuid("submitted_by_user_id").references(() => users.id, { onDelete: "set null" }),
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("mission_part_results_mission_idx").on(table.missionId),
  check("mission_part_results_status_check", sql`${table.status} IN ('draft', 'submitted', 'accepted', 'rejected')`),
]);

export const missionChecklistItems = pgTable("mission_checklist_items", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  sequence: integer("sequence").notNull(),
  prompt: text("prompt").notNull(),
  responseType: text("response_type").notNull().default("check"),
  required: boolean("required").notNull().default(true),
  responseText: text("response_text"),
  completedByUserId: uuid("completed_by_user_id").references(() => users.id, { onDelete: "set null" }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("mission_checklist_items_sequence_idx").on(table.missionId, table.sequence),
  check("mission_checklist_items_sequence_check", sql`${table.sequence} > 0`),
  check("mission_checklist_items_response_type_check", sql`${table.responseType} IN ('check', 'text', 'photo', 'video', 'number')`),
]);

export const missionEvidence = pgTable("mission_evidence", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  missionUpdateId: uuid("mission_update_id").references(() => missionUpdates.id, { onDelete: "set null" }),
  checklistItemId: uuid("checklist_item_id").references(() => missionChecklistItems.id, { onDelete: "set null" }),
  uploadedByUserId: uuid("uploaded_by_user_id").references(() => users.id, { onDelete: "set null" }),
  kind: text("kind").notNull().default("general_result"),
  storagePath: text("storage_path").notNull(),
  contentType: text("content_type"),
  byteSize: integer("byte_size"),
  caption: text("caption"),
  capturedAt: timestamp("captured_at", { withTimezone: true }),
  latitude: numeric("latitude", { precision: 9, scale: 6 }),
  longitude: numeric("longitude", { precision: 9, scale: 6 }),
  customerVisible: boolean("customer_visible").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("mission_evidence_storage_path_idx").on(table.storagePath),
  index("mission_evidence_mission_kind_idx").on(table.missionId, table.kind),
  index("mission_evidence_checklist_idx").on(table.checklistItemId),
  check("mission_evidence_kind_check", sql`${table.kind} IN ('general_result', 'delivery_photo', 'checklist_photo', 'checklist_video', 'signature')`),
  check("mission_evidence_byte_size_check", sql`${table.byteSize} IS NULL OR ${table.byteSize} >= 0`),
]);

export const missionMessages = pgTable("mission_messages", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  senderId: uuid("sender_id").notNull().references(() => users.id),
  body: text("body").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_messages_mission_idx").on(table.missionId),
  index("mission_messages_sender_idx").on(table.senderId),
]);

export const missionReviews = pgTable("mission_reviews", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  customerId: uuid("customer_id").notNull().references(() => users.id),
  scoutId: uuid("scout_id").notNull().references(() => users.id),
  rating: integer("rating").notNull(),
  review: text("review"),
  tipCents: integer("tip_cents").notNull().default(0),
  tipStatus: paymentStatus("tip_status").notNull().default("unpaid"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("mission_reviews_mission_idx").on(table.missionId),
  index("mission_reviews_scout_idx").on(table.scoutId),
]);

export const missionCases = pgTable("mission_cases", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  reporterId: uuid("reporter_id").notNull().references(() => users.id),
  kind: text("kind").notNull(),
  status: text("status").notNull().default("open"),
  previousMissionStatus: text("previous_mission_status").notNull(),
  summary: text("summary").notNull(),
  adminNotes: text("admin_notes"),
  resolution: text("resolution"),
  refundAmountCents: integer("refund_amount_cents").notNull().default(0),
  payoutAmountCents: integer("payout_amount_cents").notNull().default(0),
  resolvedBy: uuid("resolved_by").references(() => users.id),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_cases_mission_idx").on(table.missionId),
  index("mission_cases_status_idx").on(table.status),
  index("mission_cases_reporter_idx").on(table.reporterId),
]);

export const notifications = pgTable("notifications", {
  id: uuid("id").defaultRandom().primaryKey(),
  recipientUserId: uuid("recipient_user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  missionId: uuid("mission_id").references(() => missions.id, { onDelete: "cascade" }),
  channel: notificationChannel("channel").notNull().default("in_app"),
  status: notificationStatus("status").notNull().default("pending"),
  kind: text("kind").notNull(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  actionLabel: text("action_label"),
  actionUrl: text("action_url"),
  providerMessageId: text("provider_message_id"),
  error: text("error"),
  attemptCount: integer("attempt_count").notNull().default(0),
  lastAttemptAt: timestamp("last_attempt_at", { withTimezone: true }),
  readAt: timestamp("read_at", { withTimezone: true }),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("notifications_recipient_idx").on(table.recipientUserId),
  index("notifications_mission_idx").on(table.missionId),
]);

export const payments = pgTable("payments", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id),
  stripePaymentIntentId: text("stripe_payment_intent_id").notNull(),
  stripeTransferId: text("stripe_transfer_id"),
  amountCents: integer("amount_cents").notNull(),
  scoutPayoutCents: integer("scout_payout_cents").notNull(),
  platformFeeCents: integer("platform_fee_cents").notNull(),
  status: paymentStatus("status").notNull().default("unpaid"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("payments_payment_intent_idx").on(table.stripePaymentIntentId),
  index("payments_mission_idx").on(table.missionId),
]);

export const operationalEvents = pgTable("operational_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  severity: text("severity").notNull().default("error"),
  category: text("category").notNull(),
  message: text("message").notNull(),
  fingerprint: text("fingerprint").notNull(),
  contextJson: text("context_json"),
  status: text("status").notNull().default("open"),
  occurrenceCount: integer("occurrence_count").notNull().default(1),
  firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).defaultNow().notNull(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).defaultNow().notNull(),
  alertedAt: timestamp("alerted_at", { withTimezone: true }),
  acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
  acknowledgedBy: uuid("acknowledged_by").references(() => users.id),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("operational_events_fingerprint_idx").on(table.fingerprint),
  index("operational_events_status_idx").on(table.status),
  index("operational_events_last_seen_idx").on(table.lastSeenAt),
]);
