import { sql } from "drizzle-orm";
import {
  type AnyPgColumn,
  boolean,
  check,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

export const userRole = pgEnum("user_role", ["customer", "scout", "admin"]);
export const accountStatus = pgEnum("account_status", ["pending", "active", "suspended"]);
export const scoutStatus = pgEnum("scout_status", ["applicant", "review", "approved", "paused", "rejected"]);
export const verificationStatus = pgEnum("verification_status", ["not_started", "pending", "clear", "review", "failed"]);
export const missionType = pgEnum("mission_type", ["see", "move", "meet"]);
export const missionStatus = pgEnum("mission_status", [
  "draft",
  "open",
  "claimed",
  "en_route",
  "onsite",
  "en_route_pickup",
  "at_pickup",
  "en_route_dropoff",
  "at_dropoff",
  "submitted",
  "completed",
  "cancelled",
  "disputed",
]);
export const paymentStatus = pgEnum("payment_status", [
  "unpaid",
  "pending",
  "requires_action",
  "processing",
  "authorized",
  "paid",
  "partially_refunded",
  "refunded",
  "failed",
  "cancelled",
  "disputed",
]);
export const paymentTransactionStatus = pgEnum("payment_transaction_status", [
  "pending",
  "requires_action",
  "processing",
  "authorized",
  "paid",
  "partially_refunded",
  "refunded",
  "failed",
  "canceled",
  "disputed",
]);
export const payoutTransferStatus = pgEnum("payout_transfer_status", ["pending", "processing", "succeeded", "partially_reversed", "reversed", "failed"]);
export const stripePayoutStatus = pgEnum("stripe_payout_status", ["pending", "in_transit", "paid", "failed", "canceled"]);
export const stripeRefundStatus = pgEnum("stripe_refund_status", ["pending", "requires_action", "succeeded", "failed", "canceled"]);
export const stripeWebhookStatus = pgEnum("stripe_webhook_status", ["received", "processing", "processed", "failed", "ignored"]);
export const notificationChannel = pgEnum("notification_channel", ["in_app", "sms", "email"]);
export const notificationStatus = pgEnum("notification_status", ["pending", "sent", "failed"]);

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  clerkUserId: text("clerk_user_id").notNull(),
  role: userRole("role").notNull().default("customer"),
  status: accountStatus("status").notNull().default("active"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  email: text("email").notNull(),
  stripeCustomerId: text("stripe_customer_id"),
  stripeCustomerLivemode: boolean("stripe_customer_livemode"),
  phone: text("phone"),
  addressLine1: text("address_line_1"),
  addressLine2: text("address_line_2"),
  city: text("city"),
  state: text("state"),
  zip: text("zip"),
  profileCompletedAt: timestamp("profile_completed_at", { withTimezone: true }),
  emailNotificationsEnabled: boolean("email_notifications_enabled").notNull().default(true),
  smsNotificationsEnabled: boolean("sms_notifications_enabled").notNull().default(false),
  smsConsentedAt: timestamp("sms_consented_at", { withTimezone: true }),
  legalVersion: text("legal_version"),
  legalAcceptedAt: timestamp("legal_accepted_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("users_clerk_user_id_idx").on(table.clerkUserId),
  uniqueIndex("users_email_idx").on(table.email),
  uniqueIndex("users_stripe_customer_idx").on(table.stripeCustomerId),
]);

export const legalAcceptances = pgTable("legal_acceptances", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  role: userRole("role").notNull(),
  legalVersion: text("legal_version").notNull(),
  termsVersion: text("terms_version").notNull(),
  privacyVersion: text("privacy_version").notNull(),
  policiesVersion: text("policies_version").notNull(),
  arbitrationAccepted: boolean("arbitration_accepted").notNull(),
  electronicRecordsAccepted: boolean("electronic_records_accepted").notNull(),
  source: text("source").notNull().default("web"),
  userAgent: text("user_agent"),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("legal_acceptances_user_version_idx").on(table.userId, table.legalVersion),
  index("legal_acceptances_user_idx").on(table.userId),
]);

export const scoutProfiles = pgTable("scout_profiles", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  status: scoutStatus("status").notNull().default("applicant"),
  backgroundCheck: verificationStatus("background_check").notNull().default("not_started"),
  identityCheck: verificationStatus("identity_check").notNull().default("not_started"),
  identityProvider: text("identity_provider"),
  identityVerificationReference: text("identity_verification_reference"),
  identityVerifiedName: text("identity_verified_name"),
  identityVerifiedAt: timestamp("identity_verified_at", { withTimezone: true }),
  identityVerifiedBy: uuid("identity_verified_by").references(() => users.id),
  homeZip: text("home_zip"),
  serviceRadiusMiles: integer("service_radius_miles").notNull().default(25),
  vehicleType: text("vehicle_type"),
  experience: text("experience"),
  canSee: boolean("can_see").notNull().default(true),
  canMove: boolean("can_move").notNull().default(true),
  canMeet: boolean("can_meet").notNull().default(true),
  stripeAccountId: text("stripe_account_id"),
  stripeAccountApiVersion: text("stripe_account_api_version"),
  stripeAccountLivemode: boolean("stripe_account_livemode"),
  stripeConnectStatus: text("stripe_connect_status").notNull().default("not_started"),
  stripeDetailsSubmitted: boolean("stripe_details_submitted").notNull().default(false),
  stripeTransfersActive: boolean("stripe_transfers_active").notNull().default(false),
  payoutsEnabled: boolean("payouts_enabled").notNull().default(false),
  stripeRequirementsCurrentlyDue: jsonb("stripe_requirements_currently_due").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  stripeRequirementsPastDue: jsonb("stripe_requirements_past_due").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  stripeRequirementsPendingVerification: jsonb("stripe_requirements_pending_verification").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  stripeRequirementsFutureDue: jsonb("stripe_requirements_future_due").$type<string[]>().notNull().default(sql`'[]'::jsonb`),
  stripeDisabledReason: text("stripe_disabled_reason"),
  stripeConnectSyncedAt: timestamp("stripe_connect_synced_at", { withTimezone: true }),
  stripeOnboardingCompletedAt: timestamp("stripe_onboarding_completed_at", { withTimezone: true }),
  stripePayoutScheduleConfiguredAt: timestamp("stripe_payout_schedule_configured_at", { withTimezone: true }),
  verificationConsentedAt: timestamp("verification_consented_at", { withTimezone: true }),
  handbookVersion: text("handbook_version"),
  handbookAcceptedAt: timestamp("handbook_accepted_at", { withTimezone: true }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  rating: numeric("rating", { precision: 3, scale: 2 }),
  ratingCount: integer("rating_count").notNull().default(0),
  completedMissions: integer("completed_missions").notNull().default(0),
  headshotPath: text("headshot_path"),
  headshotUploadWindowStartedAt: timestamp("headshot_upload_window_started_at", { withTimezone: true }),
  headshotUploadCount: integer("headshot_upload_count").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("scout_profiles_user_id_idx").on(table.userId),
  uniqueIndex("scout_profiles_stripe_account_idx").on(table.stripeAccountId),
  check("scout_profiles_stripe_api_version_check", sql`${table.stripeAccountApiVersion} IS NULL OR ${table.stripeAccountApiVersion} IN ('v1', 'v2')`),
  check("scout_profiles_stripe_identity_check", sql`(${table.stripeAccountId} IS NULL AND ${table.stripeAccountApiVersion} IS NULL) OR (${table.stripeAccountId} IS NOT NULL AND ${table.stripeAccountApiVersion} IS NOT NULL)`),
  check("scout_profiles_stripe_status_check", sql`${table.stripeConnectStatus} IN ('not_started', 'onboarding', 'pending', 'ready', 'restricted', 'disabled')`),
  check("scout_profiles_handbook_acceptance_check", sql`(${table.handbookVersion} IS NULL AND ${table.handbookAcceptedAt} IS NULL) OR (${table.handbookVersion} IS NOT NULL AND ${table.handbookAcceptedAt} IS NOT NULL)`),
  check("scout_profiles_headshot_upload_count_check", sql`${table.headshotUploadCount} >= 0`),
]);

export const scoutHandbookAcceptances = pgTable("scout_handbook_acceptances", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  handbookVersion: text("handbook_version").notNull(),
  source: text("source").notNull(),
  userAgent: text("user_agent"),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("scout_handbook_acceptances_user_version_idx").on(table.userId, table.handbookVersion),
  index("scout_handbook_acceptances_user_idx").on(table.userId),
  check("scout_handbook_acceptances_source_check", sql`${table.source} IN ('onboarding', 'dashboard')`),
]);

export const businessAccounts = pgTable("business_accounts", {
  id: uuid("id").defaultRandom().primaryKey(),
  ownerUserId: uuid("owner_user_id").notNull().references(() => users.id),
  name: text("name").notNull(),
  status: text("status").notNull().default("active"),
  plan: text("plan").notNull().default("free"),
  billingEmail: text("billing_email"),
  stripeCustomerId: text("stripe_customer_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("business_accounts_owner_idx").on(table.ownerUserId),
  uniqueIndex("business_accounts_stripe_customer_idx").on(table.stripeCustomerId),
  check("business_accounts_status_check", sql`${table.status} IN ('active', 'paused', 'closed')`),
]);

export const businessMembers = pgTable("business_members", {
  id: uuid("id").defaultRandom().primaryKey(),
  businessAccountId: uuid("business_account_id").notNull().references(() => businessAccounts.id, { onDelete: "cascade" }),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  role: text("role").notNull().default("requester"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("business_members_account_user_idx").on(table.businessAccountId, table.userId),
  index("business_members_user_idx").on(table.userId),
  check("business_members_role_check", sql`${table.role} IN ('owner', 'admin', 'requester', 'viewer')`),
]);

export const customerSavedLocations = pgTable("customer_saved_locations", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  businessAccountId: uuid("business_account_id").references(() => businessAccounts.id, { onDelete: "cascade" }),
  label: text("label").notNull(),
  addressLine1: text("address_line_1").notNull(),
  addressLine2: text("address_line_2"),
  city: text("city").notNull(),
  state: text("state").notNull(),
  zip: text("zip").notNull(),
  latitude: numeric("latitude", { precision: 9, scale: 6 }),
  longitude: numeric("longitude", { precision: 9, scale: 6 }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("customer_saved_locations_customer_idx").on(table.customerId),
  index("customer_saved_locations_business_idx").on(table.businessAccountId),
]);

export const missionTemplates = pgTable("mission_templates", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  businessAccountId: uuid("business_account_id").references(() => businessAccounts.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  type: missionType("type").notNull(),
  configurationJson: jsonb("configuration_json").$type<Record<string, unknown>>().notNull(),
  preferredScoutId: uuid("preferred_scout_id").references(() => users.id, { onDelete: "set null" }),
  lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_templates_customer_idx").on(table.customerId),
  index("mission_templates_business_idx").on(table.businessAccountId),
]);

export const missionRecurrences = pgTable("mission_recurrences", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  businessAccountId: uuid("business_account_id").references(() => businessAccounts.id, { onDelete: "cascade" }),
  templateId: uuid("template_id").notNull().references(() => missionTemplates.id, { onDelete: "cascade" }),
  status: text("status").notNull().default("active"),
  recurrenceRule: text("recurrence_rule").notNull(),
  timezone: text("timezone").notNull().default("America/New_York"),
  startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
  endsAt: timestamp("ends_at", { withTimezone: true }),
  nextRunAt: timestamp("next_run_at", { withTimezone: true }),
  lastRunAt: timestamp("last_run_at", { withTimezone: true }),
  preferredScoutId: uuid("preferred_scout_id").references(() => users.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_recurrences_due_idx").on(table.status, table.nextRunAt),
  index("mission_recurrences_customer_idx").on(table.customerId),
  check("mission_recurrences_status_check", sql`${table.status} IN ('active', 'paused', 'ended')`),
]);

export const missionBundles = pgTable("mission_bundles", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id),
  businessAccountId: uuid("business_account_id").references(() => businessAccounts.id, { onDelete: "set null" }),
  title: text("title").notNull(),
  status: text("status").notNull().default("draft"),
  activeSequence: integer("active_sequence").notNull().default(1),
  listCustomerPriceCents: integer("list_customer_price_cents").notNull().default(0),
  bundleDiscountCents: integer("bundle_discount_cents").notNull().default(0),
  customerPriceCents: integer("customer_price_cents").notNull().default(0),
  scoutPayoutCents: integer("scout_payout_cents").notNull().default(0),
  platformFeeCents: integer("platform_fee_cents").notNull().default(0),
  paymentStatus: paymentStatus("payment_status").notNull().default("unpaid"),
  stripePaymentIntentId: text("stripe_payment_intent_id"),
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_bundles_customer_idx").on(table.customerId),
  index("mission_bundles_business_idx").on(table.businessAccountId),
  index("mission_bundles_status_idx").on(table.status),
  uniqueIndex("mission_bundles_payment_intent_idx").on(table.stripePaymentIntentId),
  check("mission_bundles_status_check", sql`${table.status} IN ('draft', 'open', 'claimed', 'in_progress', 'submitted', 'completed', 'cancelled', 'disputed')`),
  check("mission_bundles_active_sequence_check", sql`${table.activeSequence} > 0`),
  check("mission_bundles_amounts_check", sql`${table.listCustomerPriceCents} >= 0 AND ${table.bundleDiscountCents} >= 0 AND ${table.customerPriceCents} >= 0 AND ${table.scoutPayoutCents} >= 0 AND ${table.platformFeeCents} >= 0 AND ${table.bundleDiscountCents} <= ${table.listCustomerPriceCents} AND ${table.customerPriceCents} = ${table.listCustomerPriceCents} - ${table.bundleDiscountCents} AND ${table.platformFeeCents} = ${table.customerPriceCents} - ${table.scoutPayoutCents}`),
]);

export const missions = pgTable("missions", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id),
  scoutId: uuid("scout_id").references(() => users.id),
  bundleId: uuid("bundle_id").references(() => missionBundles.id),
  bundleSequence: integer("bundle_sequence"),
  predecessorMissionId: uuid("predecessor_mission_id").references((): AnyPgColumn => missions.id, { onDelete: "set null" }),
  sourceMissionId: uuid("source_mission_id").references((): AnyPgColumn => missions.id, { onDelete: "set null" }),
  templateId: uuid("template_id").references(() => missionTemplates.id, { onDelete: "set null" }),
  recurrenceId: uuid("recurrence_id").references(() => missionRecurrences.id, { onDelete: "set null" }),
  recurrenceOccurrenceAt: timestamp("recurrence_occurrence_at", { withTimezone: true }),
  preferredScoutId: uuid("preferred_scout_id").references(() => users.id, { onDelete: "set null" }),
  preferredScoutExclusiveUntil: timestamp("preferred_scout_exclusive_until", { withTimezone: true }),
  preferredScoutBroadcastAt: timestamp("preferred_scout_broadcast_at", { withTimezone: true }),
  scoutDisplayNameSnapshot: text("scout_display_name_snapshot"),
  scoutHeadshotPathSnapshot: text("scout_headshot_path_snapshot"),
  scoutIdentityVerifiedAtSnapshot: timestamp("scout_identity_verified_at_snapshot", { withTimezone: true }),
  type: missionType("type").notNull(),
  status: missionStatus("status").notNull().default("draft"),
  title: text("title").notNull(),
  instructions: text("instructions").notNull(),
  addressLine1: text("address_line_1").notNull(),
  addressLine2: text("address_line_2"),
  city: text("city").notNull(),
  state: text("state").notNull(),
  zip: text("zip").notNull(),
  pickupName: text("pickup_name"),
  pickupInstructions: text("pickup_instructions"),
  dropoffName: text("dropoff_name"),
  dropoffAddressLine1: text("dropoff_address_line_1"),
  dropoffAddressLine2: text("dropoff_address_line_2"),
  dropoffCity: text("dropoff_city"),
  dropoffState: text("dropoff_state"),
  dropoffZip: text("dropoff_zip"),
  deliveryInstructions: text("delivery_instructions"),
  deliveryPinRequired: boolean("delivery_pin_required").notNull().default(false),
  deliveryPinHash: text("delivery_pin_hash"),
  deliveryPinHint: text("delivery_pin_hint"),
  deliveryPinFailedAttempts: integer("delivery_pin_failed_attempts").notNull().default(0),
  deliveryPinLockedUntil: timestamp("delivery_pin_locked_until", { withTimezone: true }),
  deliveryPinVerifiedAt: timestamp("delivery_pin_verified_at", { withTimezone: true }),
  deliveryPinVerifiedBy: uuid("delivery_pin_verified_by").references(() => users.id, { onDelete: "set null" }),
  proofOfDeliveryRequired: boolean("proof_of_delivery_required").notNull().default(false),
  enhancedReportRequested: boolean("enhanced_report_requested").notNull().default(false),
  resultUploadTokenCount: integer("result_upload_token_count").notNull().default(0),
  largeItem: boolean("large_item").notNull().default(false),
  scheduledFor: timestamp("scheduled_for", { withTimezone: true }),
  timezone: text("timezone").notNull().default("America/New_York"),
  pickupLatitude: numeric("pickup_latitude", { precision: 9, scale: 6 }),
  pickupLongitude: numeric("pickup_longitude", { precision: 9, scale: 6 }),
  dropoffLatitude: numeric("dropoff_latitude", { precision: 9, scale: 6 }),
  dropoffLongitude: numeric("dropoff_longitude", { precision: 9, scale: 6 }),
  routeDistanceMeters: integer("route_distance_meters"),
  routeDurationSeconds: integer("route_duration_seconds"),
  routePolyline: text("route_polyline"),
  routeSource: text("route_source").notNull().default("fixed"),
  routeQuotedAt: timestamp("route_quoted_at", { withTimezone: true }),
  meetAuthorizedMinutes: integer("meet_authorized_minutes").notNull().default(60),
  maximumCustomerPriceCents: integer("maximum_customer_price_cents"),
  maximumScoutPayoutCents: integer("maximum_scout_payout_cents"),
  billableStartedAt: timestamp("billable_started_at", { withTimezone: true }),
  billableEndedAt: timestamp("billable_ended_at", { withTimezone: true }),
  billableLastVerifiedAt: timestamp("billable_last_verified_at", { withTimezone: true }),
  billableMinutes: integer("billable_minutes"),
  chargedMinutes: integer("charged_minutes"),
  verifiedCheckInAt: timestamp("verified_check_in_at", { withTimezone: true }),
  verifiedCheckInLatitude: numeric("verified_check_in_latitude", { precision: 9, scale: 6 }),
  verifiedCheckInLongitude: numeric("verified_check_in_longitude", { precision: 9, scale: 6 }),
  verifiedCheckInAccuracyMeters: integer("verified_check_in_accuracy_meters"),
  verifiedCheckOutAt: timestamp("verified_check_out_at", { withTimezone: true }),
  verifiedCheckOutLatitude: numeric("verified_check_out_latitude", { precision: 9, scale: 6 }),
  verifiedCheckOutLongitude: numeric("verified_check_out_longitude", { precision: 9, scale: 6 }),
  verifiedCheckOutAccuracyMeters: integer("verified_check_out_accuracy_meters"),
  customerPriceCents: integer("customer_price_cents").notNull(),
  listCustomerPriceCents: integer("list_customer_price_cents"),
  bundleDiscountCents: integer("bundle_discount_cents").notNull().default(0),
  scoutPayoutCents: integer("scout_payout_cents").notNull(),
  platformFeeCents: integer("platform_fee_cents").notNull(),
  paymentStatus: paymentStatus("payment_status").notNull().default("unpaid"),
  stripePaymentIntentId: text("stripe_payment_intent_id"),
  locationSharingActive: boolean("location_sharing_active").notNull().default(false),
  scoutLatitude: numeric("scout_latitude", { precision: 9, scale: 6 }),
  scoutLongitude: numeric("scout_longitude", { precision: 9, scale: 6 }),
  scoutLocationAccuracyMeters: integer("scout_location_accuracy_meters"),
  scoutLocationUpdatedAt: timestamp("scout_location_updated_at", { withTimezone: true }),
  claimedAt: timestamp("claimed_at", { withTimezone: true }),
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  archivedReason: text("archived_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("missions_status_idx").on(table.status),
  index("missions_customer_idx").on(table.customerId),
  index("missions_scout_idx").on(table.scoutId),
  index("missions_zip_idx").on(table.zip),
  index("missions_archived_idx").on(table.archivedAt),
  index("missions_bundle_idx").on(table.bundleId),
  uniqueIndex("missions_bundle_sequence_idx").on(table.bundleId, table.bundleSequence),
  index("missions_predecessor_idx").on(table.predecessorMissionId),
  index("missions_template_idx").on(table.templateId),
  index("missions_recurrence_idx").on(table.recurrenceId),
  uniqueIndex("missions_recurrence_occurrence_idx").on(table.recurrenceId, table.recurrenceOccurrenceAt),
  index("missions_preferred_scout_idx").on(table.preferredScoutId, table.preferredScoutExclusiveUntil),
  check("missions_bundle_pair_check", sql`(${table.bundleId} IS NULL AND ${table.bundleSequence} IS NULL) OR (${table.bundleId} IS NOT NULL AND ${table.bundleSequence} IS NOT NULL AND ${table.bundleSequence} > 0)`),
  check("missions_delivery_pin_check", sql`NOT ${table.deliveryPinRequired} OR (${table.type} = 'move' AND ${table.deliveryPinHash} IS NOT NULL)`),
  check("missions_delivery_pin_attempts_check", sql`${table.deliveryPinFailedAttempts} >= 0`),
  check("missions_result_upload_token_count_check", sql`${table.resultUploadTokenCount} >= 0 AND ${table.resultUploadTokenCount} <= 30`),
  check("missions_proof_delivery_check", sql`NOT ${table.proofOfDeliveryRequired} OR ${table.type} = 'move'`),
  check("missions_timezone_check", sql`${table.timezone} IN ('America/New_York', 'America/Chicago', 'America/Denver', 'America/Phoenix', 'America/Los_Angeles', 'America/Anchorage', 'Pacific/Honolulu')`),
  check("missions_financial_amounts_check", sql`${table.customerPriceCents} >= 0 AND ${table.scoutPayoutCents} >= 0 AND ${table.platformFeeCents} >= 0 AND ${table.customerPriceCents} = ${table.scoutPayoutCents} + ${table.platformFeeCents}`),
  check("missions_feature_pricing_check", sql`${table.bundleDiscountCents} >= 0 AND (${table.listCustomerPriceCents} IS NULL OR (${table.listCustomerPriceCents} >= 0 AND ${table.bundleDiscountCents} <= ${table.listCustomerPriceCents}))`),
]);

export const missionUpdates = pgTable("mission_updates", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  authorId: uuid("author_id").references(() => users.id),
  status: missionStatus("status"),
  message: text("message"),
  mediaUrl: text("media_url"),
  evidenceKind: text("evidence_kind"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [index("mission_updates_mission_idx").on(table.missionId)]);

export const customerPreferredScouts = pgTable("customer_preferred_scouts", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  scoutId: uuid("scout_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  sourceMissionId: uuid("source_mission_id").references(() => missions.id, { onDelete: "set null" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("customer_preferred_scouts_pair_idx").on(table.customerId, table.scoutId),
  index("customer_preferred_scouts_scout_idx").on(table.scoutId),
  check("customer_preferred_scouts_distinct_users_check", sql`${table.customerId} <> ${table.scoutId}`),
]);

export const missionChangeOrders = pgTable("mission_change_orders", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  proposedByUserId: uuid("proposed_by_user_id").notNull().references(() => users.id),
  kind: text("kind").notNull(),
  status: text("status").notNull().default("pending"),
  description: text("description").notNull(),
  customerDeltaCents: integer("customer_delta_cents").notNull().default(0),
  scoutDeltaCents: integer("scout_delta_cents").notNull().default(0),
  platformDeltaCents: integer("platform_delta_cents").notNull().default(0),
  linkedMissionId: uuid("linked_mission_id").references(() => missions.id, { onDelete: "set null" }),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  approvedByUserId: uuid("approved_by_user_id").references(() => users.id, { onDelete: "set null" }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  declinedAt: timestamp("declined_at", { withTimezone: true }),
  fulfilledAt: timestamp("fulfilled_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_change_orders_mission_idx").on(table.missionId),
  index("mission_change_orders_status_idx").on(table.status),
  uniqueIndex("mission_change_orders_one_pending_idx").on(table.missionId).where(sql`${table.status} = 'pending'`),
  check("mission_change_orders_status_check", sql`${table.status} IN ('pending', 'approved', 'declined', 'expired', 'fulfilled', 'cancelled')`),
  check("mission_change_orders_amounts_check", sql`${table.customerDeltaCents} >= 0 AND ${table.scoutDeltaCents} >= 0 AND ${table.platformDeltaCents} >= 0 AND ${table.customerDeltaCents} = ${table.scoutDeltaCents} + ${table.platformDeltaCents}`),
]);

export const missionPartResults = pgTable("mission_part_results", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  status: text("status").notNull().default("draft"),
  summary: text("summary"),
  submittedByUserId: uuid("submitted_by_user_id").references(() => users.id, { onDelete: "set null" }),
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  acceptedAt: timestamp("accepted_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("mission_part_results_mission_idx").on(table.missionId),
  check("mission_part_results_status_check", sql`${table.status} IN ('draft', 'submitted', 'accepted', 'rejected')`),
]);

export const missionChecklistItems = pgTable("mission_checklist_items", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  sequence: integer("sequence").notNull(),
  prompt: text("prompt").notNull(),
  responseType: text("response_type").notNull().default("check"),
  required: boolean("required").notNull().default(true),
  responseText: text("response_text"),
  completedByUserId: uuid("completed_by_user_id").references(() => users.id, { onDelete: "set null" }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("mission_checklist_items_sequence_idx").on(table.missionId, table.sequence),
  check("mission_checklist_items_sequence_check", sql`${table.sequence} > 0`),
  check("mission_checklist_items_response_type_check", sql`${table.responseType} IN ('check', 'text', 'photo', 'video', 'number')`),
]);

export const missionEvidence = pgTable("mission_evidence", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  missionUpdateId: uuid("mission_update_id").references(() => missionUpdates.id, { onDelete: "set null" }),
  checklistItemId: uuid("checklist_item_id").references(() => missionChecklistItems.id, { onDelete: "set null" }),
  uploadedByUserId: uuid("uploaded_by_user_id").references(() => users.id, { onDelete: "set null" }),
  kind: text("kind").notNull().default("general_result"),
  storagePath: text("storage_path").notNull(),
  contentType: text("content_type"),
  byteSize: integer("byte_size"),
  caption: text("caption"),
  capturedAt: timestamp("captured_at", { withTimezone: true }),
  latitude: numeric("latitude", { precision: 9, scale: 6 }),
  longitude: numeric("longitude", { precision: 9, scale: 6 }),
  customerVisible: boolean("customer_visible").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("mission_evidence_storage_path_idx").on(table.storagePath),
  index("mission_evidence_mission_kind_idx").on(table.missionId, table.kind),
  index("mission_evidence_checklist_idx").on(table.checklistItemId),
  check("mission_evidence_kind_check", sql`${table.kind} IN ('general_result', 'delivery_photo', 'checklist_photo', 'checklist_video', 'signature')`),
  check("mission_evidence_byte_size_check", sql`${table.byteSize} IS NULL OR ${table.byteSize} >= 0`),
]);

export const missionMessages = pgTable("mission_messages", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  senderId: uuid("sender_id").notNull().references(() => users.id),
  body: text("body").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_messages_mission_idx").on(table.missionId),
  index("mission_messages_sender_idx").on(table.senderId),
]);

export const missionReviews = pgTable("mission_reviews", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  customerId: uuid("customer_id").notNull().references(() => users.id),
  scoutId: uuid("scout_id").notNull().references(() => users.id),
  rating: integer("rating").notNull(),
  review: text("review"),
  tipCents: integer("tip_cents").notNull().default(0),
  tipStatus: paymentStatus("tip_status").notNull().default("unpaid"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("mission_reviews_mission_idx").on(table.missionId),
  index("mission_reviews_scout_idx").on(table.scoutId),
]);

export const missionCases = pgTable("mission_cases", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  reporterId: uuid("reporter_id").notNull().references(() => users.id),
  kind: text("kind").notNull(),
  status: text("status").notNull().default("open"),
  previousMissionStatus: text("previous_mission_status").notNull(),
  summary: text("summary").notNull(),
  adminNotes: text("admin_notes"),
  resolution: text("resolution"),
  refundAmountCents: integer("refund_amount_cents").notNull().default(0),
  payoutAmountCents: integer("payout_amount_cents").notNull().default(0),
  resolvedBy: uuid("resolved_by").references(() => users.id),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_cases_mission_idx").on(table.missionId),
  index("mission_cases_status_idx").on(table.status),
  index("mission_cases_reporter_idx").on(table.reporterId),
]);

export const customerSupportTickets = pgTable("customer_support_tickets", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  missionId: uuid("mission_id").references(() => missions.id, { onDelete: "set null" }),
  reason: text("reason").notNull(),
  summary: text("summary").notNull(),
  status: text("status").notNull().default("open"),
  resolutionType: text("resolution_type"),
  resolutionAmountCents: integer("resolution_amount_cents").notNull().default(0),
  resolutionNote: text("resolution_note"),
  proposedBy: uuid("proposed_by").references(() => users.id, { onDelete: "set null" }),
  proposedAt: timestamp("proposed_at", { withTimezone: true }),
  financialApprovedBy: uuid("financial_approved_by").references(() => users.id, { onDelete: "set null" }),
  financialApprovedAt: timestamp("financial_approved_at", { withTimezone: true }),
  customerDecision: text("customer_decision"),
  customerDecisionNote: text("customer_decision_note"),
  decidedAt: timestamp("decided_at", { withTimezone: true }),
  closedAt: timestamp("closed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("customer_support_tickets_customer_idx").on(table.customerId),
  index("customer_support_tickets_mission_idx").on(table.missionId),
  index("customer_support_tickets_status_idx").on(table.status),
  check("customer_support_tickets_reason_check", sql`${table.reason} IN ('mission_not_completed', 'mission_quality', 'scout_conduct', 'delivery_problem', 'billing_question', 'account_technical', 'other')`),
  check("customer_support_tickets_status_check", sql`${table.status} IN ('open', 'awaiting_customer', 'closed')`),
  check("customer_support_tickets_resolution_check", sql`${table.resolutionType} IS NULL OR ${table.resolutionType} IN ('full_refund', 'partial_refund', 'account_credit')`),
  check("customer_support_tickets_decision_check", sql`${table.customerDecision} IS NULL OR ${table.customerDecision} IN ('approved', 'needs_review')`),
  check("customer_support_tickets_amount_check", sql`${table.resolutionAmountCents} >= 0`),
]);

export const customerSupportMessages = pgTable("customer_support_messages", {
  id: uuid("id").defaultRandom().primaryKey(),
  ticketId: uuid("ticket_id").notNull().references(() => customerSupportTickets.id, { onDelete: "cascade" }),
  authorId: uuid("author_id").notNull().references(() => users.id),
  authorRole: text("author_role").notNull(),
  body: text("body").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("customer_support_messages_ticket_idx").on(table.ticketId),
  check("customer_support_messages_role_check", sql`${table.authorRole} IN ('customer', 'admin')`),
]);

export const customerCredits = pgTable("customer_credits", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  ticketId: uuid("ticket_id").notNull().references(() => customerSupportTickets.id, { onDelete: "restrict" }),
  amountCents: integer("amount_cents").notNull(),
  remainingAmountCents: integer("remaining_amount_cents").notNull(),
  status: text("status").notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("customer_credits_customer_idx").on(table.customerId),
  uniqueIndex("customer_credits_ticket_idx").on(table.ticketId),
  check("customer_credits_amount_check", sql`${table.amountCents} > 0 AND ${table.remainingAmountCents} >= 0 AND ${table.remainingAmountCents} <= ${table.amountCents}`),
  check("customer_credits_status_check", sql`${table.status} IN ('active', 'used', 'void')`),
]);

export const notifications = pgTable("notifications", {
  id: uuid("id").defaultRandom().primaryKey(),
  recipientUserId: uuid("recipient_user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  missionId: uuid("mission_id").references(() => missions.id, { onDelete: "cascade" }),
  channel: notificationChannel("channel").notNull().default("in_app"),
  status: notificationStatus("status").notNull().default("pending"),
  kind: text("kind").notNull(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  actionLabel: text("action_label"),
  actionUrl: text("action_url"),
  providerMessageId: text("provider_message_id"),
  error: text("error"),
  attemptCount: integer("attempt_count").notNull().default(0),
  lastAttemptAt: timestamp("last_attempt_at", { withTimezone: true }),
  readAt: timestamp("read_at", { withTimezone: true }),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("notifications_recipient_idx").on(table.recipientUserId),
  index("notifications_mission_idx").on(table.missionId),
]);

export const payments = pgTable("payments", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id),
  bundleId: uuid("bundle_id").references(() => missionBundles.id),
  customerId: uuid("customer_id").notNull().references(() => users.id),
  missionChangeOrderId: uuid("mission_change_order_id").references(() => missionChangeOrders.id),
  missionReviewId: uuid("mission_review_id").references(() => missionReviews.id),
  kind: text("kind").notNull().default("booking"),
  currency: text("currency").notNull().default("usd"),
  stripeCustomerId: text("stripe_customer_id"),
  livemode: boolean("livemode"),
  stripeCheckoutSessionId: text("stripe_checkout_session_id"),
  stripePaymentIntentId: text("stripe_payment_intent_id"),
  stripeChargeId: text("stripe_charge_id"),
  stripeBalanceTransactionId: text("stripe_balance_transaction_id"),
  stripeFeeCents: integer("stripe_fee_cents"),
  stripeNetCents: integer("stripe_net_cents"),
  legacyStripeTransferId: text("legacy_stripe_transfer_id"),
  stripeTransferGroup: text("stripe_transfer_group").notNull(),
  idempotencyKey: text("idempotency_key").notNull(),
  amountCents: integer("amount_cents").notNull(),
  scoutPayoutCents: integer("scout_payout_cents").notNull(),
  platformFeeCents: integer("platform_fee_cents").notNull(),
  refundedAmountCents: integer("refunded_amount_cents").notNull().default(0),
  status: paymentTransactionStatus("status").notNull().default("pending"),
  failureCode: text("failure_code"),
  failureMessage: text("failure_message"),
  paidAt: timestamp("paid_at", { withTimezone: true }),
  failedAt: timestamp("failed_at", { withTimezone: true }),
  cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
  disputedAt: timestamp("disputed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("payments_payment_intent_idx").on(table.stripePaymentIntentId),
  uniqueIndex("payments_checkout_session_idx").on(table.stripeCheckoutSessionId),
  uniqueIndex("payments_charge_idx").on(table.stripeChargeId),
  uniqueIndex("payments_idempotency_idx").on(table.idempotencyKey),
  uniqueIndex("payments_booking_mission_idx").on(table.missionId).where(sql`${table.kind} = 'booking'`),
  uniqueIndex("payments_booking_bundle_idx").on(table.bundleId).where(sql`${table.kind} = 'booking' AND ${table.bundleId} IS NOT NULL`),
  uniqueIndex("payments_meet_adjustment_idx").on(table.missionId).where(sql`${table.kind} = 'meet_adjustment'`),
  uniqueIndex("payments_change_order_idx").on(table.missionChangeOrderId).where(sql`${table.missionChangeOrderId} IS NOT NULL`),
  uniqueIndex("payments_review_idx").on(table.missionReviewId).where(sql`${table.missionReviewId} IS NOT NULL`),
  index("payments_mission_idx").on(table.missionId),
  index("payments_bundle_idx").on(table.bundleId),
  index("payments_customer_idx").on(table.customerId),
  index("payments_status_idx").on(table.status, table.updatedAt),
  check("payments_kind_check", sql`${table.kind} IN ('booking', 'meet_adjustment', 'change_order', 'tip', 'manual', 'duplicate')`),
  check("payments_kind_scope_check", sql`(${table.kind} = 'change_order' AND ${table.missionChangeOrderId} IS NOT NULL AND ${table.missionReviewId} IS NULL) OR (${table.kind} = 'tip' AND ${table.missionReviewId} IS NOT NULL AND ${table.missionChangeOrderId} IS NULL) OR (${table.kind} IN ('booking', 'meet_adjustment', 'manual', 'duplicate') AND ${table.missionChangeOrderId} IS NULL AND ${table.missionReviewId} IS NULL)`),
  check("payments_currency_check", sql`${table.currency} = 'usd'`),
  check("payments_amounts_check", sql`${table.amountCents} >= 0 AND ${table.scoutPayoutCents} >= 0 AND ${table.platformFeeCents} >= 0 AND ${table.amountCents} = ${table.scoutPayoutCents} + ${table.platformFeeCents} AND ${table.refundedAmountCents} >= 0 AND ${table.refundedAmountCents} <= ${table.amountCents}`),
  check("payments_bundle_scope_check", sql`${table.bundleId} IS NULL OR ${table.kind} = 'booking'`),
]);

export const paymentTransfers = pgTable("payment_transfers", {
  id: uuid("id").defaultRandom().primaryKey(),
  paymentId: uuid("payment_id").notNull().references(() => payments.id),
  missionId: uuid("mission_id").notNull().references(() => missions.id),
  bundleId: uuid("bundle_id").references(() => missionBundles.id),
  scoutId: uuid("scout_id").notNull().references(() => users.id),
  stripeAccountId: text("stripe_account_id").notNull(),
  kind: text("kind").notNull().default("mission"),
  amountCents: integer("amount_cents").notNull(),
  currency: text("currency").notNull().default("usd"),
  sourceChargeId: text("source_charge_id").notNull(),
  stripeTransferGroup: text("stripe_transfer_group").notNull(),
  stripeTransferId: text("stripe_transfer_id"),
  idempotencyKey: text("idempotency_key").notNull(),
  status: payoutTransferStatus("status").notNull().default("pending"),
  reversedAmountCents: integer("reversed_amount_cents").notNull().default(0),
  attemptCount: integer("attempt_count").notNull().default(0),
  failureCode: text("failure_code"),
  failureMessage: text("failure_message"),
  nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }).defaultNow().notNull(),
  transferredAt: timestamp("transferred_at", { withTimezone: true }),
  reversedAt: timestamp("reversed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("payment_transfers_stripe_idx").on(table.stripeTransferId),
  uniqueIndex("payment_transfers_idempotency_idx").on(table.idempotencyKey),
  uniqueIndex("payment_transfers_payment_idx").on(table.paymentId),
  index("payment_transfers_mission_idx").on(table.missionId),
  index("payment_transfers_source_charge_idx").on(table.sourceChargeId),
  index("payment_transfers_status_idx").on(table.status, table.nextAttemptAt),
  index("payment_transfers_scout_idx").on(table.scoutId, table.createdAt),
  check("payment_transfers_kind_check", sql`${table.kind} IN ('mission', 'tip', 'adjustment', 'manual')`),
  check("payment_transfers_amounts_check", sql`${table.amountCents} > 0 AND ${table.reversedAmountCents} >= 0 AND ${table.reversedAmountCents} <= ${table.amountCents}`),
  check("payment_transfers_currency_check", sql`${table.currency} = 'usd'`),
]);

export const paymentTransferReversals = pgTable("payment_transfer_reversals", {
  id: uuid("id").defaultRandom().primaryKey(),
  transferId: uuid("transfer_id").notNull().references(() => paymentTransfers.id),
  amountCents: integer("amount_cents").notNull(),
  stripeReversalId: text("stripe_reversal_id"),
  idempotencyKey: text("idempotency_key").notNull(),
  status: stripeRefundStatus("status").notNull().default("pending"),
  failureMessage: text("failure_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("payment_transfer_reversals_stripe_idx").on(table.stripeReversalId),
  uniqueIndex("payment_transfer_reversals_idempotency_idx").on(table.idempotencyKey),
  index("payment_transfer_reversals_transfer_idx").on(table.transferId),
  index("payment_transfer_reversals_status_idx").on(table.status, table.updatedAt),
  check("payment_transfer_reversals_amount_check", sql`${table.amountCents} > 0`),
]);

export const paymentRefunds = pgTable("payment_refunds", {
  id: uuid("id").defaultRandom().primaryKey(),
  paymentId: uuid("payment_id").notNull().references(() => payments.id),
  missionCaseId: uuid("mission_case_id").references(() => missionCases.id),
  amountCents: integer("amount_cents").notNull(),
  currency: text("currency").notNull().default("usd"),
  reason: text("reason").notNull().default("requested_by_customer"),
  stripeRefundId: text("stripe_refund_id"),
  idempotencyKey: text("idempotency_key").notNull(),
  status: stripeRefundStatus("status").notNull().default("pending"),
  failureCode: text("failure_code"),
  failureMessage: text("failure_message"),
  refundedAt: timestamp("refunded_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("payment_refunds_stripe_idx").on(table.stripeRefundId),
  uniqueIndex("payment_refunds_idempotency_idx").on(table.idempotencyKey),
  index("payment_refunds_payment_idx").on(table.paymentId),
  index("payment_refunds_case_idx").on(table.missionCaseId),
  index("payment_refunds_status_idx").on(table.status, table.updatedAt),
  index("payment_refunds_reason_idx").on(table.reason),
  check("payment_refunds_amount_check", sql`${table.amountCents} > 0`),
  check("payment_refunds_currency_check", sql`${table.currency} = 'usd'`),
]);

export const paymentDisputes = pgTable("payment_disputes", {
  id: uuid("id").defaultRandom().primaryKey(),
  paymentId: uuid("payment_id").notNull().references(() => payments.id),
  stripeDisputeId: text("stripe_dispute_id").notNull(),
  stripeChargeId: text("stripe_charge_id").notNull(),
  amountCents: integer("amount_cents").notNull(),
  currency: text("currency").notNull().default("usd"),
  status: text("status").notNull(),
  reason: text("reason"),
  evidenceDueAt: timestamp("evidence_due_at", { withTimezone: true }),
  providerEventCreatedAt: timestamp("provider_event_created_at", { withTimezone: true }).notNull(),
  openedAt: timestamp("opened_at", { withTimezone: true }).defaultNow().notNull(),
  closedAt: timestamp("closed_at", { withTimezone: true }),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("payment_disputes_stripe_idx").on(table.stripeDisputeId),
  index("payment_disputes_payment_idx").on(table.paymentId),
  check("payment_disputes_amount_check", sql`${table.amountCents} > 0`),
  check("payment_disputes_currency_check", sql`${table.currency} = 'usd'`),
]);

export const stripePayouts = pgTable("stripe_payouts", {
  id: uuid("id").defaultRandom().primaryKey(),
  scoutProfileId: uuid("scout_profile_id").notNull().references(() => scoutProfiles.id),
  stripeAccountId: text("stripe_account_id").notNull(),
  stripePayoutId: text("stripe_payout_id").notNull(),
  amountCents: integer("amount_cents").notNull(),
  currency: text("currency").notNull().default("usd"),
  method: text("method").notNull().default("standard"),
  automatic: boolean("automatic").notNull().default(true),
  status: stripePayoutStatus("status").notNull().default("pending"),
  arrivalAt: timestamp("arrival_at", { withTimezone: true }),
  failureCode: text("failure_code"),
  failureMessage: text("failure_message"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("stripe_payouts_stripe_idx").on(table.stripePayoutId),
  index("stripe_payouts_scout_idx").on(table.scoutProfileId, table.createdAt),
  check("stripe_payouts_amount_check", sql`${table.amountCents} > 0`),
  check("stripe_payouts_currency_check", sql`${table.currency} = 'usd'`),
  check("stripe_payouts_method_check", sql`${table.method} IN ('standard', 'instant')`),
]);

export const stripeWebhookEvents = pgTable("stripe_webhook_events", {
  eventId: text("event_id").primaryKey(),
  type: text("type").notNull(),
  scope: text("scope").notNull().default("platform"),
  connectedAccountId: text("connected_account_id"),
  objectId: text("object_id"),
  livemode: boolean("livemode").notNull(),
  apiVersion: text("api_version"),
  status: stripeWebhookStatus("status").notNull().default("received"),
  attemptCount: integer("attempt_count").notNull().default(0),
  lastError: text("last_error"),
  eventCreatedAt: timestamp("event_created_at", { withTimezone: true }),
  receivedAt: timestamp("received_at", { withTimezone: true }).defaultNow().notNull(),
  processedAt: timestamp("processed_at", { withTimezone: true }),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("stripe_webhook_events_status_idx").on(table.status, table.updatedAt),
  index("stripe_webhook_events_object_idx").on(table.objectId),
  check("stripe_webhook_events_scope_check", sql`${table.scope} IN ('platform', 'connected', 'v2')`),
]);

export const operationalEvents = pgTable("operational_events", {
  id: uuid("id").defaultRandom().primaryKey(),
  severity: text("severity").notNull().default("error"),
  category: text("category").notNull(),
  message: text("message").notNull(),
  fingerprint: text("fingerprint").notNull(),
  contextJson: text("context_json"),
  status: text("status").notNull().default("open"),
  occurrenceCount: integer("occurrence_count").notNull().default(1),
  firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).defaultNow().notNull(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).defaultNow().notNull(),
  alertedAt: timestamp("alerted_at", { withTimezone: true }),
  acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true }),
  acknowledgedBy: uuid("acknowledged_by").references(() => users.id),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("operational_events_fingerprint_idx").on(table.fingerprint),
  index("operational_events_status_idx").on(table.status),
  index("operational_events_last_seen_idx").on(table.lastSeenAt),
]);
