import {
  boolean,
  index,
  integer,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

export const userRole = pgEnum("user_role", ["customer", "scout", "admin"]);
export const accountStatus = pgEnum("account_status", ["pending", "active", "suspended"]);
export const scoutStatus = pgEnum("scout_status", ["applicant", "review", "approved", "paused", "rejected"]);
export const verificationStatus = pgEnum("verification_status", ["not_started", "pending", "clear", "review", "failed"]);
export const missionType = pgEnum("mission_type", ["see", "move", "meet"]);
export const missionStatus = pgEnum("mission_status", [
  "draft",
  "open",
  "claimed",
  "en_route",
  "onsite",
  "en_route_pickup",
  "at_pickup",
  "en_route_dropoff",
  "at_dropoff",
  "submitted",
  "completed",
  "cancelled",
  "disputed",
]);
export const paymentStatus = pgEnum("payment_status", ["unpaid", "authorized", "paid", "refunded", "failed"]);
export const notificationChannel = pgEnum("notification_channel", ["in_app", "sms", "email"]);
export const notificationStatus = pgEnum("notification_status", ["pending", "sent", "failed"]);

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  clerkUserId: text("clerk_user_id").notNull(),
  role: userRole("role").notNull().default("customer"),
  status: accountStatus("status").notNull().default("active"),
  firstName: text("first_name"),
  lastName: text("last_name"),
  email: text("email").notNull(),
  phone: text("phone"),
  addressLine1: text("address_line_1"),
  addressLine2: text("address_line_2"),
  city: text("city"),
  state: text("state"),
  zip: text("zip"),
  profileCompletedAt: timestamp("profile_completed_at", { withTimezone: true }),
  emailNotificationsEnabled: boolean("email_notifications_enabled").notNull().default(true),
  smsNotificationsEnabled: boolean("sms_notifications_enabled").notNull().default(false),
  smsConsentedAt: timestamp("sms_consented_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("users_clerk_user_id_idx").on(table.clerkUserId),
  uniqueIndex("users_email_idx").on(table.email),
]);

export const scoutProfiles = pgTable("scout_profiles", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  status: scoutStatus("status").notNull().default("applicant"),
  backgroundCheck: verificationStatus("background_check").notNull().default("not_started"),
  identityCheck: verificationStatus("identity_check").notNull().default("not_started"),
  homeZip: text("home_zip"),
  serviceRadiusMiles: integer("service_radius_miles").notNull().default(25),
  vehicleType: text("vehicle_type"),
  experience: text("experience"),
  canSee: boolean("can_see").notNull().default(true),
  canMove: boolean("can_move").notNull().default(true),
  canMeet: boolean("can_meet").notNull().default(true),
  stripeAccountId: text("stripe_account_id"),
  payoutsEnabled: boolean("payouts_enabled").notNull().default(false),
  verificationConsentedAt: timestamp("verification_consented_at", { withTimezone: true }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  rating: numeric("rating", { precision: 3, scale: 2 }),
  ratingCount: integer("rating_count").notNull().default(0),
  completedMissions: integer("completed_missions").notNull().default(0),
  headshotPath: text("headshot_path"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [uniqueIndex("scout_profiles_user_id_idx").on(table.userId)]);

export const missions = pgTable("missions", {
  id: uuid("id").defaultRandom().primaryKey(),
  customerId: uuid("customer_id").notNull().references(() => users.id),
  scoutId: uuid("scout_id").references(() => users.id),
  type: missionType("type").notNull(),
  status: missionStatus("status").notNull().default("draft"),
  title: text("title").notNull(),
  instructions: text("instructions").notNull(),
  addressLine1: text("address_line_1").notNull(),
  addressLine2: text("address_line_2"),
  city: text("city").notNull(),
  state: text("state").notNull().default("NC"),
  zip: text("zip").notNull(),
  pickupName: text("pickup_name"),
  pickupInstructions: text("pickup_instructions"),
  dropoffName: text("dropoff_name"),
  dropoffAddressLine1: text("dropoff_address_line_1"),
  dropoffAddressLine2: text("dropoff_address_line_2"),
  dropoffCity: text("dropoff_city"),
  dropoffState: text("dropoff_state"),
  dropoffZip: text("dropoff_zip"),
  deliveryInstructions: text("delivery_instructions"),
  largeItem: boolean("large_item").notNull().default(false),
  scheduledFor: timestamp("scheduled_for", { withTimezone: true }),
  pickupLatitude: numeric("pickup_latitude", { precision: 9, scale: 6 }),
  pickupLongitude: numeric("pickup_longitude", { precision: 9, scale: 6 }),
  dropoffLatitude: numeric("dropoff_latitude", { precision: 9, scale: 6 }),
  dropoffLongitude: numeric("dropoff_longitude", { precision: 9, scale: 6 }),
  routeDistanceMeters: integer("route_distance_meters"),
  routeDurationSeconds: integer("route_duration_seconds"),
  routePolyline: text("route_polyline"),
  routeSource: text("route_source").notNull().default("fixed"),
  routeQuotedAt: timestamp("route_quoted_at", { withTimezone: true }),
  meetAuthorizedMinutes: integer("meet_authorized_minutes").notNull().default(60),
  maximumCustomerPriceCents: integer("maximum_customer_price_cents"),
  maximumScoutPayoutCents: integer("maximum_scout_payout_cents"),
  billableStartedAt: timestamp("billable_started_at", { withTimezone: true }),
  billableEndedAt: timestamp("billable_ended_at", { withTimezone: true }),
  billableLastVerifiedAt: timestamp("billable_last_verified_at", { withTimezone: true }),
  billableMinutes: integer("billable_minutes"),
  chargedMinutes: integer("charged_minutes"),
  verifiedCheckInAt: timestamp("verified_check_in_at", { withTimezone: true }),
  verifiedCheckInLatitude: numeric("verified_check_in_latitude", { precision: 9, scale: 6 }),
  verifiedCheckInLongitude: numeric("verified_check_in_longitude", { precision: 9, scale: 6 }),
  verifiedCheckInAccuracyMeters: integer("verified_check_in_accuracy_meters"),
  verifiedCheckOutAt: timestamp("verified_check_out_at", { withTimezone: true }),
  verifiedCheckOutLatitude: numeric("verified_check_out_latitude", { precision: 9, scale: 6 }),
  verifiedCheckOutLongitude: numeric("verified_check_out_longitude", { precision: 9, scale: 6 }),
  verifiedCheckOutAccuracyMeters: integer("verified_check_out_accuracy_meters"),
  customerPriceCents: integer("customer_price_cents").notNull(),
  scoutPayoutCents: integer("scout_payout_cents").notNull(),
  platformFeeCents: integer("platform_fee_cents").notNull(),
  paymentStatus: paymentStatus("payment_status").notNull().default("unpaid"),
  stripePaymentIntentId: text("stripe_payment_intent_id"),
  locationSharingActive: boolean("location_sharing_active").notNull().default(false),
  scoutLatitude: numeric("scout_latitude", { precision: 9, scale: 6 }),
  scoutLongitude: numeric("scout_longitude", { precision: 9, scale: 6 }),
  scoutLocationAccuracyMeters: integer("scout_location_accuracy_meters"),
  scoutLocationUpdatedAt: timestamp("scout_location_updated_at", { withTimezone: true }),
  claimedAt: timestamp("claimed_at", { withTimezone: true }),
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("missions_status_idx").on(table.status),
  index("missions_customer_idx").on(table.customerId),
  index("missions_scout_idx").on(table.scoutId),
  index("missions_zip_idx").on(table.zip),
]);

export const missionUpdates = pgTable("mission_updates", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  authorId: uuid("author_id").references(() => users.id),
  status: missionStatus("status"),
  message: text("message"),
  mediaUrl: text("media_url"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [index("mission_updates_mission_idx").on(table.missionId)]);

export const missionMessages = pgTable("mission_messages", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  senderId: uuid("sender_id").notNull().references(() => users.id),
  body: text("body").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("mission_messages_mission_idx").on(table.missionId),
  index("mission_messages_sender_idx").on(table.senderId),
]);

export const missionReviews = pgTable("mission_reviews", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id, { onDelete: "cascade" }),
  customerId: uuid("customer_id").notNull().references(() => users.id),
  scoutId: uuid("scout_id").notNull().references(() => users.id),
  rating: integer("rating").notNull(),
  review: text("review"),
  tipCents: integer("tip_cents").notNull().default(0),
  tipStatus: paymentStatus("tip_status").notNull().default("unpaid"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("mission_reviews_mission_idx").on(table.missionId),
  index("mission_reviews_scout_idx").on(table.scoutId),
]);

export const notifications = pgTable("notifications", {
  id: uuid("id").defaultRandom().primaryKey(),
  recipientUserId: uuid("recipient_user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  missionId: uuid("mission_id").references(() => missions.id, { onDelete: "cascade" }),
  channel: notificationChannel("channel").notNull().default("in_app"),
  status: notificationStatus("status").notNull().default("pending"),
  kind: text("kind").notNull(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  providerMessageId: text("provider_message_id"),
  error: text("error"),
  readAt: timestamp("read_at", { withTimezone: true }),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("notifications_recipient_idx").on(table.recipientUserId),
  index("notifications_mission_idx").on(table.missionId),
]);

export const payments = pgTable("payments", {
  id: uuid("id").defaultRandom().primaryKey(),
  missionId: uuid("mission_id").notNull().references(() => missions.id),
  stripePaymentIntentId: text("stripe_payment_intent_id").notNull(),
  stripeTransferId: text("stripe_transfer_id"),
  amountCents: integer("amount_cents").notNull(),
  scoutPayoutCents: integer("scout_payout_cents").notNull(),
  platformFeeCents: integer("platform_fee_cents").notNull(),
  status: paymentStatus("status").notNull().default("unpaid"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  uniqueIndex("payments_payment_intent_idx").on(table.stripePaymentIntentId),
  index("payments_mission_idx").on(table.missionId),
]);
