import Link from "next/link";
import { notFound } from "next/navigation";
import { SeeHeader, SeeFooter } from "@/components/see-site";
import { seeDate, seeOpportunities } from "@/lib/see-opportunities";
export const dynamic = "force-dynamic";
export const metadata = { title: "Photo Mission | Send a Scout", robots: { index: false, follow: false } };
export default async function MissionPreview({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (!/^[0-9a-f-]{36}$/i.test(id)) notFound();
  const [row] = await seeOpportunities(id);
  return <main className="see-site"><SeeHeader /><section className="see-board see-shell"><div className="see-job-detail"><Link className="see-underlink" href="/missions">← All photo missions</Link>{row ? <><span className="see-kicker" style={{marginTop:30}}>{row.city}, {row.state} {row.zip}</span><h1>{row.template.name}</h1><div className="see-pay">${(row.payout / 100).toFixed(2)} <small style={{fontSize:14,letterSpacing:0}}>Scout payout</small></div><p>{row.template.minutes} minutes estimated on location; travel time is additional.<br />Complete by <b>{seeDate(row.deadline,row.timeZone)}</b> ({row.timeZone}).{row.earliest && <> Earliest visit: {seeDate(row.earliest,row.timeZone)}.</>}</p><p>{row.access}. {row.hasVisitHours ? "Customer has specified visit hours; review them after claiming and contact support immediately if they conflict with your availability." : "Plan a safe visit within the completion window."}</p><h2>Your assignment</h2><p>Up to {row.template.maxPhotos} photos and {row.template.maxVideos} short video{row.template.maxVideos > 1 ? "s" : ""}, plus written observations.{row.additionalQuestions > 0 && ` Includes ${row.additionalQuestions} additional customer question${row.additionalQuestions > 1 ? "s" : ""}.`}</p><ul>{row.template.tasks.map(task => <li key={task.key}><b>{task.prompt}</b><p>{task.guidance}</p></li>)}</ul><p>Document what you observe. No professional diagnosis, valuation, test drive, or unauthorized access. If an item cannot be checked safely or with permission, explain why in the checklist.</p><div className="see-empty"><h2>Want this mission?</h2><p>Create or sign into your Scout account, finish the required verification and payout setup, then review and claim. The mission is not reserved during onboarding. Payout shown is the current offer; it is confirmed when you claim and paid after completion and approval.</p><Link className="button" href={`/scout?mission=${row.id}`}>Continue to claim · ${(row.payout / 100).toFixed(0)}</Link><p>Exact address, customer contacts, and private instructions become available to the assigned Scout.</p></div></> : <div className="see-empty"><h1>This mission is no longer open.</h1><p>It may have been claimed, reached its assignment cutoff, or been cancelled. Check the board for current opportunities.</p><Link className="button" href="/missions">Browse available missions</Link></div>}</div></section><SeeFooter /></main>;
}
